In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'1.0.1'

### What is a DataFrame?

In [3]:
# some python lists
names = ['Olga', 'Andrew', 'Brian', 'Telulah',
         'Nicole', 'Tilda']
ages = [29, 21, 45, 23, 39, 45]
married = [False, True, True, True, False, True]

In [4]:
# pandas series
ser  = pd.Series(names, name='name')
ser

0       Olga
1     Andrew
2      Brian
3    Telulah
4     Nicole
5      Tilda
Name: name, dtype: object

In [5]:

# pandas dataframe
df = pd.DataFrame({'name':names, 'age':ages,
                   'married':married})
df # this dictionary uses the strings(keys) as the columns of the dataframe and the variables(values) as the data

name  age  married
0     Olga   29    False
1   Andrew   21     True
2    Brian   45     True
3  Telulah   23     True
4   Nicole   39    False
5    Tilda   45     True

###### """DataFrames have two dimensions: labelled indices and columns"""

In [6]:
ser

0       Olga
1     Andrew
2      Brian
3    Telulah
4     Nicole
5      Tilda
Name: name, dtype: object

In [7]:
ser.iloc[2]

'Brian'

In [8]:
ser.loc[2]

'Brian'

In [9]:
df.iloc[2,0]

'Brian'

In [10]:
df.loc[2]

name       Brian
age           45
married     True
Name: 2, dtype: object

In [11]:
df.iloc[2]

name       Brian
age           45
married     True
Name: 2, dtype: object

In [12]:
#.ndim --> checking dimensions of series or dataframe
ser.ndim

1

In [13]:
df.ndim

2

In [14]:
#.shape
ser.shape

(6,)

In [15]:
df.shape

(6, 3)

In [16]:
# Each column in a dataframe is a series
df['age']

0    29
1    21
2    45
3    23
4    39
5    45
Name: age, dtype: int64

###### Dataframe is a collection of series collated together<br>"""word of the lecture: collate - to collect in a given (or proper) order""" 

In [17]:
df.name

0       Olga
1     Andrew
2      Brian
3    Telulah
4     Nicole
5      Tilda
Name: name, dtype: object

In [18]:
# unlike series, dataframes could be heterogenous
df.dtypes

name       object
age         int64
married      bool
dtype: object

### Creating a DataFrame

In [19]:
df

name  age  married
0     Olga   29    False
1   Andrew   21     True
2    Brian   45     True
3  Telulah   23     True
4   Nicole   39    False
5    Tilda   45     True

In [20]:
names

['Olga', 'Andrew', 'Brian', 'Telulah', 'Nicole', 'Tilda']

In [21]:
ages

[29, 21, 45, 23, 39, 45]

In [22]:
married

[False, True, True, True, False, True]

In [23]:
pd.DataFrame({'name':names, 'age':ages})

name  age
0     Olga   29
1   Andrew   21
2    Brian   45
3  Telulah   23
4   Nicole   39
5    Tilda   45

In [24]:
new_names = names + ['Ryan']

In [25]:
new_names

['Olga', 'Andrew', 'Brian', 'Telulah', 'Nicole', 'Tilda', 'Ryan']

In [26]:
len(names), len(new_names)

(6, 7)

#### More ways to DataFrame

###### dict of tuples -> like dicts of lists, but with tuples (column-wise)<br> dict of dicts -> key:value pairs with column names as keys and index-labelled key:value pairs containing values (column-wise)<br>#dict of series -> a continuation of key concept <br>#2 (column-wise)<br> list of dicts -> list of key:value pairs containing column labels and values (row-wise)

###### DataFrame using dictionary of tuples

In [27]:
tuple_names = tuple(names)
tuple_ages = tuple(ages)
tuple_married = tuple(married)

In [28]:
tuple_names

('Olga', 'Andrew', 'Brian', 'Telulah', 'Nicole', 'Tilda')

In [29]:
tuple_ages

(29, 21, 45, 23, 39, 45)

In [30]:
tuple_married

(False, True, True, True, False, True)

In [31]:
pd.DataFrame({'name':tuple_names, 'age':tuple_ages, 'married':tuple_married})

name  age  married
0     Olga   29    False
1   Andrew   21     True
2    Brian   45     True
3  Telulah   23     True
4   Nicole   39    False
5    Tilda   45     True

###### DataFrame using dictionary of series

In [32]:
series_names = pd.Series(names)

In [33]:
series_ages = pd.Series(ages)
series_married = pd.Series(married)

In [34]:
series_names

0       Olga
1     Andrew
2      Brian
3    Telulah
4     Nicole
5      Tilda
dtype: object

In [35]:
series_married

0    False
1     True
2     True
3     True
4    False
5     True
dtype: bool

In [36]:
pd.DataFrame({'name':series_names, 
              'age':series_ages, 
              'married':series_married})

name  age  married
0     Olga   29    False
1   Andrew   21     True
2    Brian   45     True
3  Telulah   23     True
4   Nicole   39    False
5    Tilda   45     True

###### DataFrame using dictionaries of a dictionary

In [37]:
pd.DataFrame({'names':{0:'Olga', 1:'Andrew'}})

names
0    Olga
1  Andrew

###### """names above is the column name, integers 0 and 1 are therow index. Olga and Andrew are the data for the names column."""

###### the enumerate function

In [38]:
enumerate(names)

In [39]:
list(enumerate(names))

[(0, 'Olga'),
 (1, 'Andrew'),
 (2, 'Brian'),
 (3, 'Telulah'),
 (4, 'Nicole'),
 (5, 'Tilda')]

In [40]:
dict_names = {k:v for k,v in enumerate(names)}
dict_names

{0: 'Olga', 1: 'Andrew', 2: 'Brian', 3: 'Telulah', 4: 'Nicole', 5: 'Tilda'}

In [41]:
dict_ages = {k:v for k,v in enumerate(ages)}
dict_ages

{0: 29, 1: 21, 2: 45, 3: 23, 4: 39, 5: 45}

In [42]:
dict_married = {k:v for k,v in enumerate(married)}
dict_married

{0: False, 1: True, 2: True, 3: True, 4: False, 5: True}

In [43]:
pd.DataFrame({'name':dict_names, 'age':dict_ages,
              'married':dict_married})

name  age  married
0     Olga   29    False
1   Andrew   21     True
2    Brian   45     True
3  Telulah   23     True
4   Nicole   39    False
5    Tilda   45     True

In [44]:
def convert_list_to_dict(l):
    return {k:v for k,v in enumerate(l)} # In this fuction, l is the list

In [45]:
dict_names = convert_list_to_dict(names)
dict_ages = convert_list_to_dict(ages)
dict_married = convert_list_to_dict(married)

In [46]:
pd.DataFrame({'name':dict_names,
              'age':dict_ages,
              'married':dict_married})

name  age  married
0     Olga   29    False
1   Andrew   21     True
2    Brian   45     True
3  Telulah   23     True
4   Nicole   39    False
5    Tilda   45     True

In [47]:
print({k:v for k,v in enumerate(names)}) # dictionary comprehension

{0: 'Olga', 1: 'Andrew', 2: 'Brian', 3: 'Telulah', 4: 'Nicole', 5: 'Tilda'}


In [48]:
list((k+v for k,v in enumerate(married)) )

[0, 2, 3, 4, 4, 6]

###### DataFrame using list of dicts

In [49]:
pd.DataFrame([{'name':'Olga',
               'age':29,
               'married':False}])

name  age  married
0  Olga   29    False

In [50]:
list(zip(names, ages, married))

[('Olga', 29, False),
 ('Andrew', 21, True),
 ('Brian', 45, True),
 ('Telulah', 23, True),
 ('Nicole', 39, False),
 ('Tilda', 45, True)]

In [51]:
rowise = [{'name':name, 'age':age, 'married':married} for name, age, married in zip(names, ages, married)]

In [52]:
rowise

[{'name': 'Olga', 'age': 29, 'married': False},
 {'name': 'Andrew', 'age': 21, 'married': True},
 {'name': 'Brian', 'age': 45, 'married': True},
 {'name': 'Telulah', 'age': 23, 'married': True},
 {'name': 'Nicole', 'age': 39, 'married': False},
 {'name': 'Tilda', 'age': 45, 'married': True}]

In [53]:
pd.DataFrame(rowise)

name  age  married
0     Olga   29    False
1   Andrew   21     True
2    Brian   45     True
3  Telulah   23     True
4   Nicole   39    False
5    Tilda   45     True

#### The info() Method

In [54]:
 df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   name     6 non-null      object
 1   age      6 non-null      int64 
 2   married  6 non-null      bool  
dtypes: bool(1), int64(1), object(1)
memory usage: 230.0+ bytes


In [55]:
df.info(verbose=False, memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Columns: 3 entries, name to married
dtypes: bool(1), int64(1), object(1)
memory usage: 557.0 bytes


In [56]:
df.info(max_cols=2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Columns: 3 entries, name to married
dtypes: bool(1), int64(1), object(1)
memory usage: 230.0+ bytes


### Reading in Nutrition Data

In [57]:
nutrition = pd.read_csv("nutrition.csv")

In [58]:
nutrition.head()

Unnamed: 0             name serving_size  calories total_fat saturated_fat  \
0           0       Cornstarch        100 g       381      0.1g           NaN   
1           1     Nuts, pecans        100 g       691       72g          6.2g   
2           2    Eggplant, raw        100 g        25      0.2g           NaN   
3           3   Teff, uncooked        100 g       367      2.4g          0.4g   
4           4  Sherbet, orange        100 g       144        2g          1.2g   

  cholesterol    sodium  choline     folate  ...      fat  \
0           0   9.00 mg   0.4 mg   0.00 mcg  ...   0.05 g   
1           0   0.00 mg  40.5 mg  22.00 mcg  ...  71.97 g   
2           0   2.00 mg   6.9 mg  22.00 mcg  ...   0.18 g   
3           0  12.00 mg  13.1 mg          0  ...   2.38 g   
4         1mg  46.00 mg   7.7 mg   4.00 mcg  ...   2.00 g   

  saturated_fatty_acids monounsaturated_fatty_acids  \
0               0.009 g                     0.016 g   
1               6.180 g                    40.801 g   
2               0.034 g                     0.016 g   
3               0.449 g                     0.589 g   
4               1.160 g                     0.530 g   

  polyunsaturated_fatty_acids fatty_acids_total_trans alcohol     ash  \
0                     0.025 g                 0.00 mg   0.0 g  0.09 g   
1                    21.614 g                 0.00 mg   0.0 g  1.49 g   
2                     0.076 g                 0.00 mg   0.0 g  0.66 g   
3                     1.071 g                       0       0  2.37 g   
4                     0.080 g                 1.00 mg   0.0 g  0.40 g   

  caffeine theobromine    water  
0  0.00 mg     0.00 mg   8.32 g  
1  0.00 mg     0.00 mg   3.52 g  
2  0.00 mg     0.00 mg  92.30 g  
3        0           0   8.82 g  
4  0.00 mg     0.00 mg  66.10 g  

[5 rows x 77 columns]

In [59]:
nutrition.info(verbose=False, memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8789 entries, 0 to 8788
Columns: 77 entries, Unnamed: 0 to water
dtypes: int64(3), object(74)
memory usage: 39.9 MB


In [60]:
#Cleanup: Removing The Duuplicted Index

In [61]:
nutrition['Unnamed: 0']

0          0
1          1
2          2
3          3
4          4
        ... 
8784    8784
8785    8785
8786    8786
8787    8787
8788    8788
Name: Unnamed: 0, Length: 8789, dtype: int64

In [62]:
nutrition.drop('Unnamed: 0', axis=1) # axis=1 tells the unnamed column is in a column and not a row

name serving_size  \
0                                            Cornstarch        100 g   
1                                          Nuts, pecans        100 g   
2                                         Eggplant, raw        100 g   
3                                        Teff, uncooked        100 g   
4                                       Sherbet, orange        100 g   
...                                                 ...          ...   
8784  Beef, raw, all grades, trimmed to 0" fat, sepa...        100 g   
8785  Lamb, cooked, separable lean only, composite o...        100 g   
8786  Lamb, raw, separable lean and fat, composite o...        100 g   
8787  Beef, raw, all grades, trimmed to 0" fat, sepa...        100 g   
8788  Beef, raw, all grades, trimmed to 0" fat, sepa...        100 g   

      calories total_fat saturated_fat cholesterol    sodium  choline  \
0          381      0.1g           NaN           0   9.00 mg   0.4 mg   
1          691       72g          6.2g           0   0.00 mg  40.5 mg   
2           25      0.2g           NaN           0   2.00 mg   6.9 mg   
3          367      2.4g          0.4g           0  12.00 mg  13.1 mg   
4          144        2g          1.2g         1mg  46.00 mg   7.7 mg   
...        ...       ...           ...         ...       ...      ...   
8784       125      3.5g          1.4g        62mg  54.00 mg  64.5 mg   
8785       206      8.9g          3.9g       109mg  50.00 mg        0   
8786       277       23g           12g        78mg  39.00 mg        0   
8787       121        3g          1.1g        60mg  53.00 mg  64.2 mg   
8788       121        3g          1.1g        60mg  53.00 mg  64.2 mg   

         folate folic_acid  ...      fat saturated_fatty_acids  \
0      0.00 mcg   0.00 mcg  ...   0.05 g               0.009 g   
1     22.00 mcg   0.00 mcg  ...  71.97 g               6.180 g   
2     22.00 mcg   0.00 mcg  ...   0.18 g               0.034 g   
3             0          0  ...   2.38 g               0.449 g   
4      4.00 mcg   0.00 mcg  ...   2.00 g               1.160 g   
...         ...        ...  ...      ...                   ...   
8784   4.00 mcg   0.00 mcg  ...   3.50 g               1.353 g   
8785   0.00 mcg   0.00 mcg  ...   8.86 g               3.860 g   
8786   1.00 mcg   0.00 mcg  ...  22.74 g              11.570 g   
8787   4.00 mcg   0.00 mcg  ...   3.04 g               1.086 g   
8788   4.00 mcg   0.00 mcg  ...   3.04 g               1.086 g   

     monounsaturated_fatty_acids polyunsaturated_fatty_acids  \
0                        0.016 g                     0.025 g   
1                       40.801 g                    21.614 g   
2                        0.016 g                     0.076 g   
3                        0.589 g                     1.071 g   
4                        0.530 g                     0.080 g   
...                          ...                         ...   
8784                     1.554 g                     0.244 g   
8785                     3.480 g                     0.520 g   
8786                     8.720 g                     0.980 g   
8787                     1.266 g                     0.233 g   
8788                     1.266 g                     0.233 g   

     fatty_acids_total_trans alcohol     ash caffeine theobromine    water  
0                    0.00 mg   0.0 g  0.09 g  0.00 mg     0.00 mg   8.32 g  
1                    0.00 mg   0.0 g  1.49 g  0.00 mg     0.00 mg   3.52 g  
2                    0.00 mg   0.0 g  0.66 g  0.00 mg     0.00 mg  92.30 g  
3                          0       0  2.37 g        0           0   8.82 g  
4                    1.00 mg   0.0 g  0.40 g  0.00 mg     0.00 mg  66.10 g  
...                      ...     ...     ...      ...         ...      ...  
8784                62.00 mg   0.0 g  1.11 g  0.00 mg     0.00 mg  72.51 g  
8785               109.00 mg       0  1.60 g        0           0  59.95 g  
8786                78.00 mg       0  0.92 g        0 

In [63]:
nutrition.head()

Unnamed: 0             name serving_size  calories total_fat saturated_fat  \
0           0       Cornstarch        100 g       381      0.1g           NaN   
1           1     Nuts, pecans        100 g       691       72g          6.2g   
2           2    Eggplant, raw        100 g        25      0.2g           NaN   
3           3   Teff, uncooked        100 g       367      2.4g          0.4g   
4           4  Sherbet, orange        100 g       144        2g          1.2g   

  cholesterol    sodium  choline     folate  ...      fat  \
0           0   9.00 mg   0.4 mg   0.00 mcg  ...   0.05 g   
1           0   0.00 mg  40.5 mg  22.00 mcg  ...  71.97 g   
2           0   2.00 mg   6.9 mg  22.00 mcg  ...   0.18 g   
3           0  12.00 mg  13.1 mg          0  ...   2.38 g   
4         1mg  46.00 mg   7.7 mg   4.00 mcg  ...   2.00 g   

  saturated_fatty_acids monounsaturated_fatty_acids  \
0               0.009 g                     0.016 g   
1               6.180 g                    40.801 g   
2               0.034 g                     0.016 g   
3               0.449 g                     0.589 g   
4               1.160 g                     0.530 g   

  polyunsaturated_fatty_acids fatty_acids_total_trans alcohol     ash  \
0                     0.025 g                 0.00 mg   0.0 g  0.09 g   
1                    21.614 g                 0.00 mg   0.0 g  1.49 g   
2                     0.076 g                 0.00 mg   0.0 g  0.66 g   
3                     1.071 g                       0       0  2.37 g   
4                     0.080 g                 1.00 mg   0.0 g  0.40 g   

  caffeine theobromine    water  
0  0.00 mg     0.00 mg   8.32 g  
1  0.00 mg     0.00 mg   3.52 g  
2  0.00 mg     0.00 mg  92.30 g  
3        0           0   8.82 g  
4  0.00 mg     0.00 mg  66.10 g  

[5 rows x 77 columns]

In [64]:
nutrition.set_index('Unnamed: 0').head()

name serving_size  calories total_fat saturated_fat  \
Unnamed: 0                                                                   
0                Cornstarch        100 g       381      0.1g           NaN   
1              Nuts, pecans        100 g       691       72g          6.2g   
2             Eggplant, raw        100 g        25      0.2g           NaN   
3            Teff, uncooked        100 g       367      2.4g          0.4g   
4           Sherbet, orange        100 g       144        2g          1.2g   

           cholesterol    sodium  choline     folate folic_acid  ...      fat  \
Unnamed: 0                                                       ...            
0                    0   9.00 mg   0.4 mg   0.00 mcg   0.00 mcg  ...   0.05 g   
1                    0   0.00 mg  40.5 mg  22.00 mcg   0.00 mcg  ...  71.97 g   
2                    0   2.00 mg   6.9 mg  22.00 mcg   0.00 mcg  ...   0.18 g   
3                    0  12.00 mg  13.1 mg          0          0  ...   2.38 g   
4                  1mg  46.00 mg   7.7 mg   4.00 mcg   0.00 mcg  ...   2.00 g   

           saturated_fatty_acids monounsaturated_fatty_acids  \
Unnamed: 0                                                     
0                        0.009 g                     0.016 g   
1                        6.180 g                    40.801 g   
2                        0.034 g                     0.016 g   
3                        0.449 g                     0.589 g   
4                        1.160 g                     0.530 g   

           polyunsaturated_fatty_acids fatty_acids_total_trans alcohol  \
Unnamed: 0                                                               
0                              0.025 g                 0.00 mg   0.0 g   
1                             21.614 g                 0.00 mg   0.0 g   
2                              0.076 g                 0.00 mg   0.0 g   
3                              1.071 g                       0       0   
4                              0.080 g                 1.00 mg   0.0 g   

               ash caffeine theobromine    water  
Unnamed: 0                                        
0           0.09 g  0.00 mg     0.00 mg   8.32 g  
1           1.49 g  0.00 mg     0.00 mg   3.52 g  
2           0.66 g  0.00 mg     0.00 mg  92.30 g  
3           2.37 g        0           0   8.82 g  
4           0.40 g  0.00 mg     0.00 mg  66.10 g  

[5 rows x 76 columns]

In [65]:
pd.read_csv("nutrition.csv", index_col='Unnamed: 0')

name serving_size  \
0                                            Cornstarch        100 g   
1                                          Nuts, pecans        100 g   
2                                         Eggplant, raw        100 g   
3                                        Teff, uncooked        100 g   
4                                       Sherbet, orange        100 g   
...                                                 ...          ...   
8784  Beef, raw, all grades, trimmed to 0" fat, sepa...        100 g   
8785  Lamb, cooked, separable lean only, composite o...        100 g   
8786  Lamb, raw, separable lean and fat, composite o...        100 g   
8787  Beef, raw, all grades, trimmed to 0" fat, sepa...        100 g   
8788  Beef, raw, all grades, trimmed to 0" fat, sepa...        100 g   

      calories total_fat saturated_fat cholesterol    sodium  choline  \
0          381      0.1g           NaN           0   9.00 mg   0.4 mg   
1          691       72g          6.2g           0   0.00 mg  40.5 mg   
2           25      0.2g           NaN           0   2.00 mg   6.9 mg   
3          367      2.4g          0.4g           0  12.00 mg  13.1 mg   
4          144        2g          1.2g         1mg  46.00 mg   7.7 mg   
...        ...       ...           ...         ...       ...      ...   
8784       125      3.5g          1.4g        62mg  54.00 mg  64.5 mg   
8785       206      8.9g          3.9g       109mg  50.00 mg        0   
8786       277       23g           12g        78mg  39.00 mg        0   
8787       121        3g          1.1g        60mg  53.00 mg  64.2 mg   
8788       121        3g          1.1g        60mg  53.00 mg  64.2 mg   

         folate folic_acid  ...      fat saturated_fatty_acids  \
0      0.00 mcg   0.00 mcg  ...   0.05 g               0.009 g   
1     22.00 mcg   0.00 mcg  ...  71.97 g               6.180 g   
2     22.00 mcg   0.00 mcg  ...   0.18 g               0.034 g   
3             0          0  ...   2.38 g               0.449 g   
4      4.00 mcg   0.00 mcg  ...   2.00 g               1.160 g   
...         ...        ...  ...      ...                   ...   
8784   4.00 mcg   0.00 mcg  ...   3.50 g               1.353 g   
8785   0.00 mcg   0.00 mcg  ...   8.86 g               3.860 g   
8786   1.00 mcg   0.00 mcg  ...  22.74 g              11.570 g   
8787   4.00 mcg   0.00 mcg  ...   3.04 g               1.086 g   
8788   4.00 mcg   0.00 mcg  ...   3.04 g               1.086 g   

     monounsaturated_fatty_acids polyunsaturated_fatty_acids  \
0                        0.016 g                     0.025 g   
1                       40.801 g                    21.614 g   
2                        0.016 g                     0.076 g   
3                        0.589 g                     1.071 g   
4                        0.530 g                     0.080 g   
...                          ...                         ...   
8784                     1.554 g                     0.244 g   
8785                     3.480 g                     0.520 g   
8786                     8.720 g                     0.980 g   
8787                     1.266 g                     0.233 g   
8788                     1.266 g                     0.233 g   

     fatty_acids_total_trans alcohol     ash caffeine theobromine    water  
0                    0.00 mg   0.0 g  0.09 g  0.00 mg     0.00 mg   8.32 g  
1                    0.00 mg   0.0 g  1.49 g  0.00 mg     0.00 mg   3.52 g  
2                    0.00 mg   0.0 g  0.66 g  0.00 mg     0.00 mg  92.30 g  
3                          0       0  2.37 g        0           0   8.82 g  
4                    1.00 mg   0.0 g  0.40 g  0.00 mg     0.00 mg  66.10 g  
...                      ...     ...     ...      ...         ...      ...  
8784                62.00 mg   0.0 g  1.11 g  0.00 mg     0.00 mg  72.51 g  
8785               109.00 mg       0  1.60 g        0           0  59.95 g  
8786                78.00 mg       0  0.92 g        0 

In [66]:
pd.read_csv("nutrition.csv", index_col=[0]) # use the first column as the index column

name serving_size  \
0                                            Cornstarch        100 g   
1                                          Nuts, pecans        100 g   
2                                         Eggplant, raw        100 g   
3                                        Teff, uncooked        100 g   
4                                       Sherbet, orange        100 g   
...                                                 ...          ...   
8784  Beef, raw, all grades, trimmed to 0" fat, sepa...        100 g   
8785  Lamb, cooked, separable lean only, composite o...        100 g   
8786  Lamb, raw, separable lean and fat, composite o...        100 g   
8787  Beef, raw, all grades, trimmed to 0" fat, sepa...        100 g   
8788  Beef, raw, all grades, trimmed to 0" fat, sepa...        100 g   

      calories total_fat saturated_fat cholesterol    sodium  choline  \
0          381      0.1g           NaN           0   9.00 mg   0.4 mg   
1          691       72g          6.2g           0   0.00 mg  40.5 mg   
2           25      0.2g           NaN           0   2.00 mg   6.9 mg   
3          367      2.4g          0.4g           0  12.00 mg  13.1 mg   
4          144        2g          1.2g         1mg  46.00 mg   7.7 mg   
...        ...       ...           ...         ...       ...      ...   
8784       125      3.5g          1.4g        62mg  54.00 mg  64.5 mg   
8785       206      8.9g          3.9g       109mg  50.00 mg        0   
8786       277       23g           12g        78mg  39.00 mg        0   
8787       121        3g          1.1g        60mg  53.00 mg  64.2 mg   
8788       121        3g          1.1g        60mg  53.00 mg  64.2 mg   

         folate folic_acid  ...      fat saturated_fatty_acids  \
0      0.00 mcg   0.00 mcg  ...   0.05 g               0.009 g   
1     22.00 mcg   0.00 mcg  ...  71.97 g               6.180 g   
2     22.00 mcg   0.00 mcg  ...   0.18 g               0.034 g   
3             0          0  ...   2.38 g               0.449 g   
4      4.00 mcg   0.00 mcg  ...   2.00 g               1.160 g   
...         ...        ...  ...      ...                   ...   
8784   4.00 mcg   0.00 mcg  ...   3.50 g               1.353 g   
8785   0.00 mcg   0.00 mcg  ...   8.86 g               3.860 g   
8786   1.00 mcg   0.00 mcg  ...  22.74 g              11.570 g   
8787   4.00 mcg   0.00 mcg  ...   3.04 g               1.086 g   
8788   4.00 mcg   0.00 mcg  ...   3.04 g               1.086 g   

     monounsaturated_fatty_acids polyunsaturated_fatty_acids  \
0                        0.016 g                     0.025 g   
1                       40.801 g                    21.614 g   
2                        0.016 g                     0.076 g   
3                        0.589 g                     1.071 g   
4                        0.530 g                     0.080 g   
...                          ...                         ...   
8784                     1.554 g                     0.244 g   
8785                     3.480 g                     0.520 g   
8786                     8.720 g                     0.980 g   
8787                     1.266 g                     0.233 g   
8788                     1.266 g                     0.233 g   

     fatty_acids_total_trans alcohol     ash caffeine theobromine    water  
0                    0.00 mg   0.0 g  0.09 g  0.00 mg     0.00 mg   8.32 g  
1                    0.00 mg   0.0 g  1.49 g  0.00 mg     0.00 mg   3.52 g  
2                    0.00 mg   0.0 g  0.66 g  0.00 mg     0.00 mg  92.30 g  
3                          0       0  2.37 g        0           0   8.82 g  
4                    1.00 mg   0.0 g  0.40 g  0.00 mg     0.00 mg  66.10 g  
...                      ...     ...     ...      ...         ...      ...  
8784                62.00 mg   0.0 g  1.11 g  0.00 mg     0.00 mg  72.51 g  
8785               109.00 mg       0  1.60 g        0           0  59.95 g  
8786                78.00 mg       0  0.92 g        0 

In [67]:
#The sample() method

In [68]:
nutrition.sample()

Unnamed: 0                                               name  \
5818        5818  Milk, with added vitamin A and vitamin D, fat ...   

     serving_size  calories total_fat saturated_fat cholesterol     sodium  \
5818        100 g        67        0g           NaN         2mg  110.00 mg   

      choline    folate  ...     fat saturated_fatty_acids  \
5818  15.6 mg  2.00 mcg  ...  0.00 g               0.000 g   

     monounsaturated_fatty_acids polyunsaturated_fatty_acids  \
5818                     0.000 g                     0.000 g   

     fatty_acids_total_trans alcohol     ash caffeine theobromine    water  
5818                 2.00 mg   0.0 g  0.81 g  1.00 mg    22.00 mg  82.34 g  

[1 rows x 77 columns]

In [69]:
nutrition.sample(random_state=12)

Unnamed: 0                                             name  \
3713        3713  Thuringer, pork, beef, summer sausage, cervelat   

     serving_size  calories total_fat saturated_fat cholesterol      sodium  \
3713        100 g       362       30g           12g        74mg  1300.00 mg   

      choline    folate  ...      fat saturated_fatty_acids  \
3713  78.9 mg  2.00 mcg  ...  30.43 g              11.510 g   

     monounsaturated_fatty_acids polyunsaturated_fatty_acids  \
3713                    12.970 g                     1.200 g   

     fatty_acids_total_trans alcohol     ash caffeine theobromine    water  
3713                74.00 mg   0.0 g  3.63 g  0.00 mg     0.00 mg  45.18 g  

[1 rows x 77 columns]

In [70]:
nutrition.sample(n=3)

Unnamed: 0                                               name  \
1954        1954                     Babyfood, orange-carrot, juice   
1203        1203                           Soy flour, raw, full-fat   
4469        4469  WORTHINGTON Smoked Turkey Roll, unprepared, fr...   

     serving_size  calories total_fat saturated_fat cholesterol     sodium  \
1954        100 g        43      0.1g           NaN           0   10.00 mg   
1203        100 g       434       21g            3g           0   13.00 mg   
4469        100 g       251       16g          2.3g           0  859.00 mg   

       choline      folate  ...      fat saturated_fatty_acids  \
1954    6.5 mg   39.00 mcg  ...   0.10 g               0.010 g   
1203  190.6 mg  345.00 mcg  ...  20.65 g               2.987 g   
4469         0           0  ...  16.10 g               2.300 g   

     monounsaturated_fatty_acids polyunsaturated_fatty_acids  \
1954                     0.010 g                     0.030 g   
1203                     4.561 g                    11.657 g   
4469                     3.900 g                     8.900 g   

     fatty_acids_total_trans alcohol     ash caffeine theobromine    water  
1954                 0.00 mg   0.0 g  0.25 g  0.00 mg     0.00 mg  89.10 g  
1203                 0.00 mg   0.0 g  4.46 g  0.00 mg     0.00 mg   5.16 g  
4469                 0.00 mg       0  3.70 g        0           0  53.70 g  

[3 rows x 77 columns]

In [71]:
nutrition.sample(frac=0.01).count()

Unnamed: 0      88
name            88
serving_size    88
calories        88
total_fat       88
                ..
alcohol         88
ash             88
caffeine        88
theobromine     88
water           88
Length: 77, dtype: int64

In [72]:
nutrition.shape[0] * 0.01

87.89

In [73]:
nutrition = nutrition.drop('Unnamed: 0', axis=1)

### Sampling With Replacement or Weights

##### sampling with or without replacement

In [74]:
nutrition.sample(n=3, replace=True)

name serving_size  \
5809  Pork, raw, frozen, ears, variety meats and by-...        100 g   
6032  Frostings, prepared with butter, dry mix, crea...        100 g   
4137  Cookies, with extra creme filling, chocolate s...        100 g   

      calories total_fat saturated_fat cholesterol     sodium choline  \
5809       234       15g          5.4g        82mg  191.00 mg       0   
6032       408       13g          8.4g        24mg  124.00 mg  2.1 mg   
4137       497       25g          5.5g           0  351.00 mg  3.3 mg   

         folate folic_acid  ...      fat saturated_fatty_acids  \
5809   0.00 mcg   0.00 mcg  ...  15.10 g               5.390 g   
6032   3.00 mcg   0.00 mcg  ...  13.06 g               8.369 g   
4137  46.00 mcg  34.00 mcg  ...  24.52 g               5.454 g   

     monounsaturated_fatty_acids polyunsaturated_fatty_acids  \
5809                     6.860 g                     1.610 g   
6032                     3.425 g                     0.496 g   
4137                    16.076 g                     2.471 g   

     fatty_acids_total_trans alcohol     ash caffeine theobromine    water  
5809                82.00 mg   0.0 g  0.60 g        0           0  61.25 g  
6032                24.00 mg   0.0 g  0.71 g  5.00 mg   146.00 mg  13.33 g  
4137                 0.00 mg   0.0 g  1.30 g  6.00 mg   190.00 mg   1.65 g  

[3 rows x 76 columns]

##### weighted sampling

In [75]:
weights = pd.Series(data=[10,10,10,1,21], index=[7,17,29,5,6])

In [76]:
weights

7     10
17    10
29    10
5      1
6     21
dtype: int64

In [77]:
nutrition.sample(n=3, weights=weights)

name serving_size  calories total_fat saturated_fat  \
6         Taro leaves, raw        100 g        42      0.7g          0.2g   
17  Peppers, raw, jalapeno        100 g        29      0.4g          0.1g   
29  Nuts, dried, pine nuts        100 g       673       68g          4.9g   

   cholesterol   sodium  choline      folate folic_acid  ...      fat  \
6            0  3.00 mg  12.8 mg  126.00 mcg   0.00 mcg  ...   0.74 g   
17           0  3.00 mg   7.5 mg   27.00 mcg   0.00 mcg  ...   0.37 g   
29           0  2.00 mg  55.8 mg   34.00 mcg   0.00 mcg  ...  68.37 g   

   saturated_fatty_acids monounsaturated_fatty_acids  \
6                0.151 g                     0.060 g   
17               0.092 g                     0.029 g   
29               4.899 g                    18.764 g   

   polyunsaturated_fatty_acids fatty_acids_total_trans alcohol     ash  \
6                      0.307 g                 0.00 mg   0.0 g  1.92 g   
17                     0.112 g                 0.00 mg   0.0 g  0.53 g   
29                    34.071 g                 0.00 mg   0.0 g  2.59 g   

   caffeine theobromine    water  
6   0.00 mg     0.00 mg  85.66 g  
17  0.00 mg     0.00 mg  91.69 g  
29  0.00 mg     0.00 mg   2.28 g  

[3 rows x 76 columns]

#### DataFrame Axes

In [78]:
nutrition.head()

name serving_size  calories total_fat saturated_fat cholesterol  \
0       Cornstarch        100 g       381      0.1g           NaN           0   
1     Nuts, pecans        100 g       691       72g          6.2g           0   
2    Eggplant, raw        100 g        25      0.2g           NaN           0   
3   Teff, uncooked        100 g       367      2.4g          0.4g           0   
4  Sherbet, orange        100 g       144        2g          1.2g         1mg   

     sodium  choline     folate folic_acid  ...      fat  \
0   9.00 mg   0.4 mg   0.00 mcg   0.00 mcg  ...   0.05 g   
1   0.00 mg  40.5 mg  22.00 mcg   0.00 mcg  ...  71.97 g   
2   2.00 mg   6.9 mg  22.00 mcg   0.00 mcg  ...   0.18 g   
3  12.00 mg  13.1 mg          0          0  ...   2.38 g   
4  46.00 mg   7.7 mg   4.00 mcg   0.00 mcg  ...   2.00 g   

  saturated_fatty_acids monounsaturated_fatty_acids  \
0               0.009 g                     0.016 g   
1               6.180 g                    40.801 g   
2               0.034 g                     0.016 g   
3               0.449 g                     0.589 g   
4               1.160 g                     0.530 g   

  polyunsaturated_fatty_acids fatty_acids_total_trans alcohol     ash  \
0                     0.025 g                 0.00 mg   0.0 g  0.09 g   
1                    21.614 g                 0.00 mg   0.0 g  1.49 g   
2                     0.076 g                 0.00 mg   0.0 g  0.66 g   
3                     1.071 g                       0       0  2.37 g   
4                     0.080 g                 1.00 mg   0.0 g  0.40 g   

  caffeine theobromine    water  
0  0.00 mg     0.00 mg   8.32 g  
1  0.00 mg     0.00 mg   3.52 g  
2  0.00 mg     0.00 mg  92.30 g  
3        0           0   8.82 g  
4  0.00 mg     0.00 mg  66.10 g  

[5 rows x 76 columns]

In [79]:
nutrition.shape

(8789, 76)

In [80]:
nutrition.axes

[RangeIndex(start=0, stop=8789, step=1),
 Index(['name', 'serving_size', 'calories', 'total_fat', 'saturated_fat',
        'cholesterol', 'sodium', 'choline', 'folate', 'folic_acid', 'niacin',
        'pantothenic_acid', 'riboflavin', 'thiamin', 'vitamin_a',
        'vitamin_a_rae', 'carotene_alpha', 'carotene_beta',
        'cryptoxanthin_beta', 'lutein_zeaxanthin', 'lucopene', 'vitamin_b12',
        'vitamin_b6', 'vitamin_c', 'vitamin_d', 'vitamin_e', 'tocopherol_alpha',
        'vitamin_k', 'calcium', 'copper', 'irom', 'magnesium', 'manganese',
        'phosphorous', 'potassium', 'selenium', 'zink', 'protein', 'alanine',
        'arginine', 'aspartic_acid', 'cystine', 'glutamic_acid', 'glycine',
        'histidine', 'hydroxyproline', 'isoleucine', 'leucine', 'lysine',
        'methionine', 'phenylalanine', 'proline', 'serine', 'threonine',
        'tryptophan', 'tyrosine', 'valine', 'carbohydrate', 'fiber', 'sugars',
        'fructose', 'galactose', 'glucose', 'lactose', 'maltose', 

In [81]:
nutrition.axes[0]

RangeIndex(start=0, stop=8789, step=1)

In [82]:
nutrition.axes[0][3]

3

In [83]:
nutrition.index

RangeIndex(start=0, stop=8789, step=1)

In [84]:
nutrition.index[3]

3

In [85]:
nutrition.axes[1]

Index(['name', 'serving_size', 'calories', 'total_fat', 'saturated_fat',
       'cholesterol', 'sodium', 'choline', 'folate', 'folic_acid', 'niacin',
       'pantothenic_acid', 'riboflavin', 'thiamin', 'vitamin_a',
       'vitamin_a_rae', 'carotene_alpha', 'carotene_beta',
       'cryptoxanthin_beta', 'lutein_zeaxanthin', 'lucopene', 'vitamin_b12',
       'vitamin_b6', 'vitamin_c', 'vitamin_d', 'vitamin_e', 'tocopherol_alpha',
       'vitamin_k', 'calcium', 'copper', 'irom', 'magnesium', 'manganese',
       'phosphorous', 'potassium', 'selenium', 'zink', 'protein', 'alanine',
       'arginine', 'aspartic_acid', 'cystine', 'glutamic_acid', 'glycine',
       'histidine', 'hydroxyproline', 'isoleucine', 'leucine', 'lysine',
       'methionine', 'phenylalanine', 'proline', 'serine', 'threonine',
       'tryptophan', 'tyrosine', 'valine', 'carbohydrate', 'fiber', 'sugars',
       'fructose', 'galactose', 'glucose', 'lactose', 'maltose', 'sucrose',
       'fat', 'saturated_fatty_acids', 'mon

In [86]:
nutrition.axes[1][69]

'polyunsaturated_fatty_acids'

In [87]:
nutrition.columns[69]

'polyunsaturated_fatty_acids'

In [88]:
nutrition.columns

Index(['name', 'serving_size', 'calories', 'total_fat', 'saturated_fat',
       'cholesterol', 'sodium', 'choline', 'folate', 'folic_acid', 'niacin',
       'pantothenic_acid', 'riboflavin', 'thiamin', 'vitamin_a',
       'vitamin_a_rae', 'carotene_alpha', 'carotene_beta',
       'cryptoxanthin_beta', 'lutein_zeaxanthin', 'lucopene', 'vitamin_b12',
       'vitamin_b6', 'vitamin_c', 'vitamin_d', 'vitamin_e', 'tocopherol_alpha',
       'vitamin_k', 'calcium', 'copper', 'irom', 'magnesium', 'manganese',
       'phosphorous', 'potassium', 'selenium', 'zink', 'protein', 'alanine',
       'arginine', 'aspartic_acid', 'cystine', 'glutamic_acid', 'glycine',
       'histidine', 'hydroxyproline', 'isoleucine', 'leucine', 'lysine',
       'methionine', 'phenylalanine', 'proline', 'serine', 'threonine',
       'tryptophan', 'tyrosine', 'valine', 'carbohydrate', 'fiber', 'sugars',
       'fructose', 'galactose', 'glucose', 'lactose', 'maltose', 'sucrose',
       'fat', 'saturated_fatty_acids', 'mon

#### Changing the index

In [89]:
nutrition.head()

name serving_size  calories total_fat saturated_fat cholesterol  \
0       Cornstarch        100 g       381      0.1g           NaN           0   
1     Nuts, pecans        100 g       691       72g          6.2g           0   
2    Eggplant, raw        100 g        25      0.2g           NaN           0   
3   Teff, uncooked        100 g       367      2.4g          0.4g           0   
4  Sherbet, orange        100 g       144        2g          1.2g         1mg   

     sodium  choline     folate folic_acid  ...      fat  \
0   9.00 mg   0.4 mg   0.00 mcg   0.00 mcg  ...   0.05 g   
1   0.00 mg  40.5 mg  22.00 mcg   0.00 mcg  ...  71.97 g   
2   2.00 mg   6.9 mg  22.00 mcg   0.00 mcg  ...   0.18 g   
3  12.00 mg  13.1 mg          0          0  ...   2.38 g   
4  46.00 mg   7.7 mg   4.00 mcg   0.00 mcg  ...   2.00 g   

  saturated_fatty_acids monounsaturated_fatty_acids  \
0               0.009 g                     0.016 g   
1               6.180 g                    40.801 g   
2               0.034 g                     0.016 g   
3               0.449 g                     0.589 g   
4               1.160 g                     0.530 g   

  polyunsaturated_fatty_acids fatty_acids_total_trans alcohol     ash  \
0                     0.025 g                 0.00 mg   0.0 g  0.09 g   
1                    21.614 g                 0.00 mg   0.0 g  1.49 g   
2                     0.076 g                 0.00 mg   0.0 g  0.66 g   
3                     1.071 g                       0       0  2.37 g   
4                     0.080 g                 1.00 mg   0.0 g  0.40 g   

  caffeine theobromine    water  
0  0.00 mg     0.00 mg   8.32 g  
1  0.00 mg     0.00 mg   3.52 g  
2  0.00 mg     0.00 mg  92.30 g  
3        0           0   8.82 g  
4  0.00 mg     0.00 mg  66.10 g  

[5 rows x 76 columns]

In [90]:
nutrition.index

RangeIndex(start=0, stop=8789, step=1)

In [91]:
nutrition.index

RangeIndex(start=0, stop=8789, step=1)

In [92]:
type(nutrition.index)

pandas.core.indexes.range.RangeIndex

In [93]:
nutrition.index = pd.RangeIndex(start=0, stop=8789, step=1)

In [94]:
type(nutrition.index)

pandas.core.indexes.range.RangeIndex

In [95]:
nutrition.set_index('name', inplace=True)

In [96]:
nutrition.set_index('folic_acid', drop=False, append=True, verify_integrity=False).head()
#verify integrity tells us about the uniqueness of our index values

serving_size  calories total_fat saturated_fat  \
name            folic_acid                                                  
Cornstarch      0.00 mcg          100 g       381      0.1g           NaN   
Nuts, pecans    0.00 mcg          100 g       691       72g          6.2g   
Eggplant, raw   0.00 mcg          100 g        25      0.2g           NaN   
Teff, uncooked  0                 100 g       367      2.4g          0.4g   
Sherbet, orange 0.00 mcg          100 g       144        2g          1.2g   

                           cholesterol    sodium  choline     folate  \
name            folic_acid                                             
Cornstarch      0.00 mcg             0   9.00 mg   0.4 mg   0.00 mcg   
Nuts, pecans    0.00 mcg             0   0.00 mg  40.5 mg  22.00 mcg   
Eggplant, raw   0.00 mcg             0   2.00 mg   6.9 mg  22.00 mcg   
Teff, uncooked  0                    0  12.00 mg  13.1 mg          0   
Sherbet, orange 0.00 mcg           1mg  46.00 mg   7.7 mg   4.00 mcg   

                           folic_acid    niacin  ...      fat  \
name            folic_acid                       ...            
Cornstarch      0.00 mcg     0.00 mcg  0.000 mg  ...   0.05 g   
Nuts, pecans    0.00 mcg     0.00 mcg  1.167 mg  ...  71.97 g   
Eggplant, raw   0.00 mcg     0.00 mcg  0.649 mg  ...   0.18 g   
Teff, uncooked  0                   0  3.363 mg  ...   2.38 g   
Sherbet, orange 0.00 mcg     0.00 mcg  0.063 mg  ...   2.00 g   

                           saturated_fatty_acids monounsaturated_fatty_acids  \
name            folic_acid                                                     
Cornstarch      0.00 mcg                 0.009 g                     0.016 g   
Nuts, pecans    0.00 mcg                 6.180 g                    40.801 g   
Eggplant, raw   0.00 mcg                 0.034 g                     0.016 g   
Teff, uncooked  0                        0.449 g                     0.589 g   
Sherbet, orange 0.00 mcg                 1.160 g                     0.530 g   

                           polyunsaturated_fatty_acids  \
name            folic_acid                               
Cornstarch      0.00 mcg                       0.025 g   
Nuts, pecans    0.00 mcg                      21.614 g   
Eggplant, raw   0.00 mcg                       0.076 g   
Teff, uncooked  0                              1.071 g   
Sherbet, orange 0.00 mcg                       0.080 g   

                           fatty_acids_total_trans alcohol     ash caffeine  \
name            folic_acid                                                    
Cornstarch      0.00 mcg                   0.00 mg   0.0 g  0.09 g  0.00 mg   
Nuts, pecans    0.00 mcg                   0.00 mg   0.0 g  1.49 g  0.00 mg   
Eggplant, raw   0.00 mcg                   0.00 mg   0.0 g  0.66 g  0.00 mg   
Teff, uncooked  0                                0       0  2.37 g        0   
Sherbet, orange 0.00 mcg                   1.00 mg   0.0 g  0.40 g  0.00 mg   

                           theobromine    water  
name            folic_acid                       
Cornstarch      0.00 mcg       0.00 mg   8.32 g  
Nuts, pecans    0.00 mcg       0.00 mg   3.52 g  
Eggplant, raw   0.00 mcg       0.00 mg  92.30 g  
Teff, uncooked  0                    0   8.82 g  
Sherbet, orange 0.00 mcg       0.00 mg  66.10 g  

[5 rows x 75 columns]

In [97]:
nutrition.columns.value_counts()

carotene_alpha    1
choline           1
zink              1
saturated_fat     1
carotene_beta     1
                 ..
manganese         1
sodium            1
arginine          1
vitamin_a_rae     1
folic_acid        1
Length: 75, dtype: int64

In [98]:
nutrition.calories.value_counts()

884    78
47     45
56     43
0      39
63     38
       ..
593     1
657     1
665     1
673     1
727     1
Name: calories, Length: 671, dtype: int64

In [99]:
nutrition.set_index('calories', verify_integrity=False)

serving_size total_fat saturated_fat cholesterol    sodium  choline  \
calories                                                                       
381             100 g      0.1g           NaN           0   9.00 mg   0.4 mg   
691             100 g       72g          6.2g           0   0.00 mg  40.5 mg   
25              100 g      0.2g           NaN           0   2.00 mg   6.9 mg   
367             100 g      2.4g          0.4g           0  12.00 mg  13.1 mg   
144             100 g        2g          1.2g         1mg  46.00 mg   7.7 mg   
...               ...       ...           ...         ...       ...      ...   
125             100 g      3.5g          1.4g        62mg  54.00 mg  64.5 mg   
206             100 g      8.9g          3.9g       109mg  50.00 mg        0   
277             100 g       23g           12g        78mg  39.00 mg        0   
121             100 g        3g          1.1g        60mg  53.00 mg  64.2 mg   
121             100 g        3g          1.1g        60mg  53.00 mg  64.2 mg   

             folate folic_acid    niacin pantothenic_acid  ...      fat  \
calories                                                   ...            
381        0.00 mcg   0.00 mcg  0.000 mg         0.000 mg  ...   0.05 g   
691       22.00 mcg   0.00 mcg  1.167 mg         0.863 mg  ...  71.97 g   
25        22.00 mcg   0.00 mcg  0.649 mg         0.281 mg  ...   0.18 g   
367               0          0  3.363 mg         0.942 mg  ...   2.38 g   
144        4.00 mcg   0.00 mcg  0.063 mg         0.224 mg  ...   2.00 g   
...             ...        ...       ...              ...  ...      ...   
125        4.00 mcg   0.00 mcg  6.422 mg         0.356 mg  ...   3.50 g   
206        0.00 mcg   0.00 mcg  7.680 mg         0.580 mg  ...   8.86 g   
277        1.00 mcg   0.00 mcg  6.550 mg         0.520 mg  ...  22.74 g   
121        4.00 mcg   0.00 mcg  6.720 mg         0.355 mg  ...   3.04 g   
121        4.00 mcg   0.00 mcg  6.720 mg         0.355 mg  ...   3.04 g   

         saturated_fatty_acids monounsaturated_fatty_acids  \
calories                                                     
381                    0.009 g                     0.016 g   
691                    6.180 g                    40.801 g   
25                     0.034 g                     0.016 g   
367                    0.449 g                     0.589 g   
144                    1.160 g                     0.530 g   
...                        ...                         ...   
125                    1.353 g                     1.554 g   
206                    3.860 g                     3.480 g   
277                   11.570 g                     8.720 g   
121                    1.086 g                     1.266 g   
121                    1.086 g                     1.266 g   

         polyunsaturated_fatty_acids fatty_acids_total_trans alcohol     ash  \
calories                                                                       
381                          0.025 g                 0.00 mg   0.0 g  0.09 g   
691                         21.614 g                 0.00 mg   0.0 g  1.49 g   
25                           0.076 g                 0.00 mg   0.0 g  0.66 g   
367                          1.071 g                       0       0  2.37 g   
144                          0.080 g                 1.00 mg   0.0 g  0.40 g   
...                              ...                     ...     ...     ...   
125                          0.244 g                62.00 mg   0.0 g  1.11 g   
206                          0.520 g               109.00 mg       0  1.60 g   
277                          0.980 g                78.00 mg       0  0.92 g   
121                          0.233 g                60.00 mg   0.0 g  1.10 g   
121                          0.233 g                60.00 mg   0.0 g  1.10 g   

         caffeine  theobromine    water  
calories                                 
381       0.00 mg      0.00 mg   8.32 g  
691       0.00 mg 

##### Exctracting from DataFrame by label

In [100]:
nutrition.head(4)

serving_size  calories total_fat saturated_fat cholesterol  \
name                                                                        
Cornstarch            100 g       381      0.1g           NaN           0   
Nuts, pecans          100 g       691       72g          6.2g           0   
Eggplant, raw         100 g        25      0.2g           NaN           0   
Teff, uncooked        100 g       367      2.4g          0.4g           0   

                  sodium  choline     folate folic_acid    niacin  ...  \
name                                                               ...   
Cornstarch       9.00 mg   0.4 mg   0.00 mcg   0.00 mcg  0.000 mg  ...   
Nuts, pecans     0.00 mg  40.5 mg  22.00 mcg   0.00 mcg  1.167 mg  ...   
Eggplant, raw    2.00 mg   6.9 mg  22.00 mcg   0.00 mcg  0.649 mg  ...   
Teff, uncooked  12.00 mg  13.1 mg          0          0  3.363 mg  ...   

                    fat saturated_fatty_acids monounsaturated_fatty_acids  \
name                                                                        
Cornstarch       0.05 g               0.009 g                     0.016 g   
Nuts, pecans    71.97 g               6.180 g                    40.801 g   
Eggplant, raw    0.18 g               0.034 g                     0.016 g   
Teff, uncooked   2.38 g               0.449 g                     0.589 g   

               polyunsaturated_fatty_acids fatty_acids_total_trans alcohol  \
name                                                                         
Cornstarch                         0.025 g                 0.00 mg   0.0 g   
Nuts, pecans                      21.614 g                 0.00 mg   0.0 g   
Eggplant, raw                      0.076 g                 0.00 mg   0.0 g   
Teff, uncooked                     1.071 g                       0       0   

                   ash caffeine theobromine    water  
name                                                  
Cornstarch      0.09 g  0.00 mg     0.00 mg   8.32 g  
Nuts, pecans    1.49 g  0.00 mg     0.00 mg   3.52 g  
Eggplant, raw   0.66 g  0.00 mg     0.00 mg  92.30 g  
Teff, uncooked  2.37 g        0           0   8.82 g  

[4 rows x 75 columns]

In [101]:
nutrition.loc['Eggplant, raw']

serving_size       100 g
calories              25
total_fat           0.2g
saturated_fat        NaN
cholesterol            0
                  ...   
alcohol            0.0 g
ash               0.66 g
caffeine         0.00 mg
theobromine      0.00 mg
water            92.30 g
Name: Eggplant, raw, Length: 75, dtype: object

In [102]:
type(nutrition.loc['Eggplant, raw'])

pandas.core.series.Series

In [103]:
nutrition.loc['Eggplant, raw']['calories']

25

In [104]:
nutrition.loc['Eggplant, raw', 'calories']#Eggplant is the row, calories is the column

25

In [105]:
nutrition.loc['Eggplant, raw':'Sherbet, orange' , 'calories':'cholesterol']

calories total_fat saturated_fat cholesterol
name                                                         
Eggplant, raw          25      0.2g           NaN           0
Teff, uncooked        367      2.4g          0.4g           0
Sherbet, orange       144        2g          1.2g         1mg

In [106]:
nutrition.loc[
              ['Raspberries, raw', 'Blackberries, raw'], # row
              ['protein', 'vitamin_b6', 'water'] # column
   ]

protein vitamin_b6    water
name                                         
Raspberries, raw   1.20 g   0.055 mg  85.75 g
Blackberries, raw  1.39 g   0.030 mg  88.15 g

##### DataFrame Extraction by position

In [107]:
nutrition.head(10)

serving_size  calories total_fat saturated_fat cholesterol  \
name                                                                            
Cornstarch                100 g       381      0.1g           NaN           0   
Nuts, pecans              100 g       691       72g          6.2g           0   
Eggplant, raw             100 g        25      0.2g           NaN           0   
Teff, uncooked            100 g       367      2.4g          0.4g           0   
Sherbet, orange           100 g       144        2g          1.2g         1mg   
Cauliflower, raw          100 g        25      0.3g          0.1g           0   
Taro leaves, raw          100 g        42      0.7g          0.2g           0   
Lamb, raw, ground         100 g       282       23g           10g        73mg   
Cheese, camembert         100 g       300       24g           15g        72mg   
Vegetarian fillets        100 g       290       18g          2.8g           0   

                       sodium  choline      folate folic_acid     niacin  ...  \
name                                                                      ...   
Cornstarch            9.00 mg   0.4 mg    0.00 mcg   0.00 mcg   0.000 mg  ...   
Nuts, pecans          0.00 mg  40.5 mg   22.00 mcg   0.00 mcg   1.167 mg  ...   
Eggplant, raw         2.00 mg   6.9 mg   22.00 mcg   0.00 mcg   0.649 mg  ...   
Teff, uncooked       12.00 mg  13.1 mg           0          0   3.363 mg  ...   
Sherbet, orange      46.00 mg   7.7 mg    4.00 mcg   0.00 mcg   0.063 mg  ...   
Cauliflower, raw     30.00 mg  44.3 mg   57.00 mcg   0.00 mcg   0.507 mg  ...   
Taro leaves, raw      3.00 mg  12.8 mg  126.00 mcg   0.00 mcg   1.513 mg  ...   
Lamb, raw, ground    59.00 mg  69.3 mg   18.00 mcg   0.00 mcg   5.960 mg  ...   
Cheese, camembert   842.00 mg  15.4 mg   62.00 mcg   0.00 mcg   0.630 mg  ...   
Vegetarian fillets  490.00 mg  82.0 mg  102.00 mcg   0.00 mcg  12.000 mg  ...   

                        fat saturated_fatty_acids monounsaturated_fatty_acids  \
name                                                                            
Cornstarch           0.05 g               0.009 g                     0.016 g   
Nuts, pecans        71.97 g               6.180 g                    40.801 g   
Eggplant, raw        0.18 g               0.034 g                     0.016 g   
Teff, uncooked       2.38 g               0.449 g                     0.589 g   
Sherbet, orange      2.00 g               1.160 g                     0.530 g   
Cauliflower, raw     0.28 g               0.130 g                     0.034 g   
Taro leaves, raw     0.74 g               0.151 g                     0.060 g   
Lamb, raw, ground   23.41 g              10.190 g                     9.600 g   
Cheese, camembert   24.26 g              15.259 g                     7.023 g   
Vegetarian fillets  18.00 g               2.849 g                     4.376 g   

                   polyunsaturated_fatty_acids fatty_acids_total_trans  \
name                                                                     
Cornstarch                             0.025 g                 0.00 mg   
Nuts, pecans                          21.614 g                 0.00 mg   
Eggplant, raw                          0.076 g                 0.00 mg   
Teff, uncooked                         1.071 g                       0   
Sherbet, orange                        0.080 g                 1.00 mg   
Cauliflower, raw                       0.031 g                 0.00 mg   
Taro leaves, raw                       0.307 g                 0.00 mg   
Lamb, raw, ground                      1.850 g                73.00 mg   
Cheese, camembert                      0.724 g                72.00 mg   
Vegetarian fillets                     9.332 g                 0.00 mg   

                   alcohol     ash caffeine theobromine    water  
name                                                              
Cornstarch           0.0 g  0.09 g  0.00 mg     0.00 mg   8.32 g  
Nuts, peca

In [108]:
nutrition.iloc[3]

serving_size      100 g
calories            367
total_fat          2.4g
saturated_fat      0.4g
cholesterol           0
                  ...  
alcohol               0
ash              2.37 g
caffeine              0
theobromine           0
water            8.82 g
Name: Teff, uncooked, Length: 75, dtype: object

In [109]:
nutrition.iloc[3,:]

serving_size      100 g
calories            367
total_fat          2.4g
saturated_fat      0.4g
cholesterol           0
                  ...  
alcohol               0
ash              2.37 g
caffeine              0
theobromine           0
water            8.82 g
Name: Teff, uncooked, Length: 75, dtype: object

In [110]:
nutrition.iloc[[4,6,8], :]

serving_size  calories total_fat saturated_fat cholesterol  \
name                                                                           
Sherbet, orange          100 g       144        2g          1.2g         1mg   
Taro leaves, raw         100 g        42      0.7g          0.2g           0   
Cheese, camembert        100 g       300       24g           15g        72mg   

                      sodium  choline      folate folic_acid    niacin  ...  \
name                                                                    ...   
Sherbet, orange     46.00 mg   7.7 mg    4.00 mcg   0.00 mcg  0.063 mg  ...   
Taro leaves, raw     3.00 mg  12.8 mg  126.00 mcg   0.00 mcg  1.513 mg  ...   
Cheese, camembert  842.00 mg  15.4 mg   62.00 mcg   0.00 mcg  0.630 mg  ...   

                       fat saturated_fatty_acids monounsaturated_fatty_acids  \
name                                                                           
Sherbet, orange     2.00 g               1.160 g                     0.530 g   
Taro leaves, raw    0.74 g               0.151 g                     0.060 g   
Cheese, camembert  24.26 g              15.259 g                     7.023 g   

                  polyunsaturated_fatty_acids fatty_acids_total_trans alcohol  \
name                                                                            
Sherbet, orange                       0.080 g                 1.00 mg   0.0 g   
Taro leaves, raw                      0.307 g                 0.00 mg   0.0 g   
Cheese, camembert                     0.724 g                72.00 mg   0.0 g   

                      ash caffeine theobromine    water  
name                                                     
Sherbet, orange    0.40 g  0.00 mg     0.00 mg  66.10 g  
Taro leaves, raw   1.92 g  0.00 mg     0.00 mg  85.66 g  
Cheese, camembert  3.68 g  0.00 mg     0.00 mg  51.80 g  

[3 rows x 75 columns]

In [111]:
nutrition.iloc[[4,6,8], 2]

name
Sherbet, orange        2g
Taro leaves, raw     0.7g
Cheese, camembert     24g
Name: total_fat, dtype: object

In [112]:
nutrition.iloc[[4,6,8], [2,3,4]]

total_fat saturated_fat cholesterol
name                                                 
Sherbet, orange          2g          1.2g         1mg
Taro leaves, raw       0.7g          0.2g           0
Cheese, camembert       24g           15g        72mg

In [113]:
#The above can aslo be done:
nutrition.iloc[[4,6,8], 2:5]

total_fat saturated_fat cholesterol
name                                                 
Sherbet, orange          2g          1.2g         1mg
Taro leaves, raw       0.7g          0.2g           0
Cheese, camembert       24g           15g        72mg

In [114]:
# boolean masks

In [115]:
nutrition.iloc[
               [True if i%2==0 else False for i in range(8789)],
               [True if i%2==0 else False for i in range(75)]
]

serving_size total_fat  \
name                                                                        
Cornstarch                                                100 g      0.1g   
Eggplant, raw                                             100 g      0.2g   
Sherbet, orange                                           100 g        2g   
Taro leaves, raw                                          100 g      0.7g   
Cheese, camembert                                         100 g       24g   
...                                                         ...       ...   
Beef, raw, select, trimmed to 1/8" fat, separab...        100 g      6.4g   
Oil, uses similar to 95 degree hard butter, con...        100 g      100g   
Beef, raw, all grades, trimmed to 0" fat, separ...        100 g      3.5g   
Lamb, raw, separable lean and fat, composite of...        100 g       23g   
Beef, raw, all grades, trimmed to 0" fat, separ...        100 g        3g   

                                                   cholesterol  choline  \
name                                                                      
Cornstarch                                                   0   0.4 mg   
Eggplant, raw                                                0   6.9 mg   
Sherbet, orange                                            1mg   7.7 mg   
Taro leaves, raw                                             0  12.8 mg   
Cheese, camembert                                         72mg  15.4 mg   
...                                                        ...      ...   
Beef, raw, select, trimmed to 1/8" fat, separab...        70mg  49.4 mg   
Oil, uses similar to 95 degree hard butter, con...           0   0.2 mg   
Beef, raw, all grades, trimmed to 0" fat, separ...        62mg  64.5 mg   
Lamb, raw, separable lean and fat, composite of...        78mg        0   
Beef, raw, all grades, trimmed to 0" fat, separ...        60mg  64.2 mg   

                                                   folic_acid  \
name                                                            
Cornstarch                                           0.00 mcg   
Eggplant, raw                                        0.00 mcg   
Sherbet, orange                                      0.00 mcg   
Taro leaves, raw                                     0.00 mcg   
Cheese, camembert                                    0.00 mcg   
...                                                       ...   
Beef, raw, select, trimmed to 1/8" fat, separab...   0.00 mcg   
Oil, uses similar to 95 degree hard butter, con...   0.00 mcg   
Beef, raw, all grades, trimmed to 0" fat, separ...   0.00 mcg   
Lamb, raw, separable lean and fat, composite of...   0.00 mcg   
Beef, raw, all grades, trimmed to 0" fat, separ...   0.00 mcg   

                                                   pantothenic_acid   thiamin  \
name                                                                            
Cornstarch                                                 0.000 mg  0.000 mg   
Eggplant, raw                                              0.281 mg  0.039 mg   
Sherbet, orange                                            0.224 mg  0.027 mg   
Taro leaves, raw                                           0.084 mg  0.209 mg   
Cheese, camembert                                          1.364 mg  0.028 mg   
...                                                             ...       ...   
Beef, raw, select, trimmed to 1/8" fat, separab...         0.530 mg  0.100 mg   
Oil, uses similar to 95 degree hard butter, con...         0.000 mg  0.000 mg   
Beef, raw, all grades, trimmed to 0" fat, separ...         0.356 mg  0.063 mg   
Lamb, raw, separable lean and fat, composite of...         0.520 mg  0.130 mg   
Beef, raw, all grades, trimmed to 0" fat, separ...         0.355 mg  0.063 mg   

                                                   vitamin_a_rae  \
name                                                               
Cornstarch                           

In [116]:
nutrition.shape

(8789, 75)

In [117]:
new_nutr = nutrition.iloc[
                          [True if i%2==0 else False for i in range(8789)],
                          [True if i%2==0 else False for i in range(75)]
                         ]

In [118]:
new_nutr.shape

(4395, 38)

In [119]:
nutrition.head(10)

serving_size  calories total_fat saturated_fat cholesterol  \
name                                                                            
Cornstarch                100 g       381      0.1g           NaN           0   
Nuts, pecans              100 g       691       72g          6.2g           0   
Eggplant, raw             100 g        25      0.2g           NaN           0   
Teff, uncooked            100 g       367      2.4g          0.4g           0   
Sherbet, orange           100 g       144        2g          1.2g         1mg   
Cauliflower, raw          100 g        25      0.3g          0.1g           0   
Taro leaves, raw          100 g        42      0.7g          0.2g           0   
Lamb, raw, ground         100 g       282       23g           10g        73mg   
Cheese, camembert         100 g       300       24g           15g        72mg   
Vegetarian fillets        100 g       290       18g          2.8g           0   

                       sodium  choline      folate folic_acid     niacin  ...  \
name                                                                      ...   
Cornstarch            9.00 mg   0.4 mg    0.00 mcg   0.00 mcg   0.000 mg  ...   
Nuts, pecans          0.00 mg  40.5 mg   22.00 mcg   0.00 mcg   1.167 mg  ...   
Eggplant, raw         2.00 mg   6.9 mg   22.00 mcg   0.00 mcg   0.649 mg  ...   
Teff, uncooked       12.00 mg  13.1 mg           0          0   3.363 mg  ...   
Sherbet, orange      46.00 mg   7.7 mg    4.00 mcg   0.00 mcg   0.063 mg  ...   
Cauliflower, raw     30.00 mg  44.3 mg   57.00 mcg   0.00 mcg   0.507 mg  ...   
Taro leaves, raw      3.00 mg  12.8 mg  126.00 mcg   0.00 mcg   1.513 mg  ...   
Lamb, raw, ground    59.00 mg  69.3 mg   18.00 mcg   0.00 mcg   5.960 mg  ...   
Cheese, camembert   842.00 mg  15.4 mg   62.00 mcg   0.00 mcg   0.630 mg  ...   
Vegetarian fillets  490.00 mg  82.0 mg  102.00 mcg   0.00 mcg  12.000 mg  ...   

                        fat saturated_fatty_acids monounsaturated_fatty_acids  \
name                                                                            
Cornstarch           0.05 g               0.009 g                     0.016 g   
Nuts, pecans        71.97 g               6.180 g                    40.801 g   
Eggplant, raw        0.18 g               0.034 g                     0.016 g   
Teff, uncooked       2.38 g               0.449 g                     0.589 g   
Sherbet, orange      2.00 g               1.160 g                     0.530 g   
Cauliflower, raw     0.28 g               0.130 g                     0.034 g   
Taro leaves, raw     0.74 g               0.151 g                     0.060 g   
Lamb, raw, ground   23.41 g              10.190 g                     9.600 g   
Cheese, camembert   24.26 g              15.259 g                     7.023 g   
Vegetarian fillets  18.00 g               2.849 g                     4.376 g   

                   polyunsaturated_fatty_acids fatty_acids_total_trans  \
name                                                                     
Cornstarch                             0.025 g                 0.00 mg   
Nuts, pecans                          21.614 g                 0.00 mg   
Eggplant, raw                          0.076 g                 0.00 mg   
Teff, uncooked                         1.071 g                       0   
Sherbet, orange                        0.080 g                 1.00 mg   
Cauliflower, raw                       0.031 g                 0.00 mg   
Taro leaves, raw                       0.307 g                 0.00 mg   
Lamb, raw, ground                      1.850 g                73.00 mg   
Cheese, camembert                      0.724 g                72.00 mg   
Vegetarian fillets                     9.332 g                 0.00 mg   

                   alcohol     ash caffeine theobromine    water  
name                                                              
Cornstarch           0.0 g  0.09 g  0.00 mg     0.00 mg   8.32 g  
Nuts, peca

In [120]:
nutrition.iloc[9,1]

290

#### Skill challenge

In [121]:
#1. Randomly select 10 food items and assign the resulting dataframe to nutr_mini

In [122]:
nutr_mini = nutrition.sample(10)

In [123]:
#2. From nutr_mini extract total_fat and cholesterol columns for all rows

In [124]:
nutr_mini.loc[:, ['total_fat', 'cholesterol']]

total_fat cholesterol
name                                                                    
Pork, raw, with added solution, separable lean ...      5.4g        59mg
Infant formula, not reconstituted, liquid conce...      6.9g         3mg
Sauce, ready-to-serve, plum                               1g           0
Melons, raw, casaba                                     0.1g           0
Beef, roasted, cooked, choice, trimmed to 0" fa...       12g        85mg
Shortening cake mix, soybean (hydrogenated) and...      100g           0
Soy flour, defatted                                     1.2g           0
MURRAY, Old Fashioned Iced Oatmeal Cookies               18g           0
Lamb, broiled, cooked, trimmed to 1/8" fat, sep...      7.7g        85mg
Cranberry-orange relish, canned                         0.1g           0

In [125]:
#3.Extract all the columns from vitamin_b12 to the end for the first, second and third row

In [126]:
nutr_mini.columns.get_loc('vitamin_b12')

20

In [127]:
nutr_mini.iloc[0:3, 20:]

vitamin_b12 vitamin_b6  \
name                                                                        
Pork, raw, with added solution, separable lean ...    0.89 mcg   0.509 mg   
Infant formula, not reconstituted, liquid conce...    0.32 mcg   0.076 mg   
Sauce, ready-to-serve, plum                           0.00 mcg   0.078 mg   

                                                   vitamin_c vitamin_d  \
name                                                                     
Pork, raw, with added solution, separable lean ...    0.0 mg  21.00 IU   
Infant formula, not reconstituted, liquid conce...   11.5 mg  76.00 IU   
Sauce, ready-to-serve, plum                           0.5 mg         0   

                                                   vitamin_e tocopherol_alpha  \
name                                                                            
Pork, raw, with added solution, separable lean ...   0.23 mg          0.23 mg   
Infant formula, not reconstituted, liquid conce...   1.28 mg          1.28 mg   
Sauce, ready-to-serve, plum                                0                0   

                                                   vitamin_k   calcium  \
name                                                                     
Pork, raw, with added solution, separable lean ...   0.0 mcg  14.00 mg   
Infant formula, not reconstituted, liquid conce...  10.2 mcg  99.00 mg   
Sauce, ready-to-serve, plum                                0  12.00 mg   

                                                      copper     irom  ...  \
name                                                                   ...   
Pork, raw, with added solution, separable lean ...  0.125 mg  1.04 mg  ...   
Infant formula, not reconstituted, liquid conce...  0.115 mg  0.89 mg  ...   
Sauce, ready-to-serve, plum                         0.078 mg  1.43 mg  ...   

                                                       fat  \
name                                                         
Pork, raw, with added solution, separable lean ...  5.36 g   
Infant formula, not reconstituted, liquid conce...  6.89 g   
Sauce, ready-to-serve, plum                         1.04 g   

                                                   saturated_fatty_acids  \
name                                                                       
Pork, raw, with added solution, separable lean ...               1.873 g   
Infant formula, not reconstituted, liquid conce...               2.401 g   
Sauce, ready-to-serve, plum                                      0.153 g   

                                                   monounsaturated_fatty_acids  \
name                                                                             
Pork, raw, with added solution, separable lean ...                     2.329 g   
Infant formula, not reconstituted, liquid conce...                     2.551 g   
Sauce, ready-to-serve, plum                                            0.240 g   

                                                   polyunsaturated_fatty_acids  \
name                                                                             
Pork, raw, with added solution, separable lean ...                     0.581 g   
Infant formula, not reconstituted, liquid conce...                     1.555 g   
Sauce, ready-to-serve, plum                                            0.588 g   

                                                   fatty_acids_total_trans  \
name                                                                         
Pork, raw, with added solution, separable lean ...                59.00 mg   
Infant formula, not reconstituted, liquid conce...                 3.00 mg   
Sauce, ready-to-serve, plum                                        0.00 mg   

                                                   alcohol     ash caffeine  \
name                                                                          
Pork, raw, with added solution, separable lean ...   0.0 g  1.3

In [128]:
#4. Get the calories for the third food in nutr_mini using an attribute based approach that is faster than .loc or .iloc

In [129]:
nutr_mini.columns.get_loc('calories')

1

In [130]:
nutr_mini.iat[2,1]

184

#### More clean-up: Going Numeric

In [131]:
nutrition.head()

serving_size  calories total_fat saturated_fat cholesterol  \
name                                                                         
Cornstarch             100 g       381      0.1g           NaN           0   
Nuts, pecans           100 g       691       72g          6.2g           0   
Eggplant, raw          100 g        25      0.2g           NaN           0   
Teff, uncooked         100 g       367      2.4g          0.4g           0   
Sherbet, orange        100 g       144        2g          1.2g         1mg   

                   sodium  choline     folate folic_acid    niacin  ...  \
name                                                                ...   
Cornstarch        9.00 mg   0.4 mg   0.00 mcg   0.00 mcg  0.000 mg  ...   
Nuts, pecans      0.00 mg  40.5 mg  22.00 mcg   0.00 mcg  1.167 mg  ...   
Eggplant, raw     2.00 mg   6.9 mg  22.00 mcg   0.00 mcg  0.649 mg  ...   
Teff, uncooked   12.00 mg  13.1 mg          0          0  3.363 mg  ...   
Sherbet, orange  46.00 mg   7.7 mg   4.00 mcg   0.00 mcg  0.063 mg  ...   

                     fat saturated_fatty_acids monounsaturated_fatty_acids  \
name                                                                         
Cornstarch        0.05 g               0.009 g                     0.016 g   
Nuts, pecans     71.97 g               6.180 g                    40.801 g   
Eggplant, raw     0.18 g               0.034 g                     0.016 g   
Teff, uncooked    2.38 g               0.449 g                     0.589 g   
Sherbet, orange   2.00 g               1.160 g                     0.530 g   

                polyunsaturated_fatty_acids fatty_acids_total_trans alcohol  \
name                                                                          
Cornstarch                          0.025 g                 0.00 mg   0.0 g   
Nuts, pecans                       21.614 g                 0.00 mg   0.0 g   
Eggplant, raw                       0.076 g                 0.00 mg   0.0 g   
Teff, uncooked                      1.071 g                       0       0   
Sherbet, orange                     0.080 g                 1.00 mg   0.0 g   

                    ash caffeine theobromine    water  
name                                                   
Cornstarch       0.09 g  0.00 mg     0.00 mg   8.32 g  
Nuts, pecans     1.49 g  0.00 mg     0.00 mg   3.52 g  
Eggplant, raw    0.66 g  0.00 mg     0.00 mg  92.30 g  
Teff, uncooked   2.37 g        0           0   8.82 g  
Sherbet, orange  0.40 g  0.00 mg     0.00 mg  66.10 g  

[5 rows x 75 columns]

In [132]:
nutrition.total_fat.head()

name
Cornstarch         0.1g
Nuts, pecans        72g
Eggplant, raw      0.2g
Teff, uncooked     2.4g
Sherbet, orange      2g
Name: total_fat, dtype: object

In [133]:
nutrition.total_fat.sum()

'0.1g72g0.2g2.4g2g0.3g0.7g23g24g18g0g0.4g0.1g7.2g15g4.5g16g0.4g0.9g9.2g0.5g1.7g5.9g33g15g0g0g3g0.4g68g1.5g0.2g11g0.8g16g0.2g0.5g50g0.3g0.6g3g16g3.1g11g2.4g0g0.3g0.5g99g0.1g5.3g5.3g0.4g5.3g0.2g0.3g6.4g22g1g14g10g17g14g4.3g22g36g0.7g100g27g2.8g5.8g14g0.7g1.5g11g34g0.2g0.9g4.6g0g0.4g19g0.2g10g28g6.7g6.7g0.3g0.3g44g37g14g50g0.9g0.7g0.1g0.7g8g10g19g9.2g0g0.2g8.6g1.3g14g0.4g0.2g8.2g5.2g3.3g2.1g0.1g80g0.5g1.4g0.4g3.3g0.2g0.7g0.1g9.4g0.3g0.6g29g0.2g1.4g0.2g0.4g1.2g1.8g0g0.9g0.2g1.4g0.8g1.5g9.8g0g13g16g19g7.4g0.2g5.2g29g0.3g9.9g22g14g15g4.1g0.5g3.5g15g20g32g1g81g0.2g1.6g0g17g22g7.1g7.4g0.2g8.7g1.4g34g0.3g6.3g30g8.1g0.2g0.1g3.7g0.6g0.3g3.9g0.3g1.2g29g14g26g1.1g2g13g0g9g22g3.7g100g0.1g2.1g2.1g0.3g0.2g6.8g8.1g8.3g2.4g0.2g23g6.7g1g0.3g0.2g0.1g12g17g0.1g100g3.4g0.2g6.7g1.5g22g0g1g25g34g3.6g100g7.3g9g1.6g0.4g0.3g18g0.4g9.5g1.4g11g3.1g1.5g0g2.4g3.6g0g15g1.2g6.6g0.7g4.2g15g0.1g0.5g0.2g0.1g3.5g3g0.1g0.4g0.1g0.3g100g31g2.8g9.7g2.3g11g1.7g0.1g1.7g0.5g4.7g0.5g0.2g8.6g18g25g0.5g0.5g26g7.7g0.1g0.1g100g1.1g16

In [134]:
'Adura' + 'Kinoshi'

'AduraKinoshi'

In [135]:
nutrition.total_fat.max() # this is because they are strings

'9g'

In [136]:
nutrition.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
Index: 8789 entries, Cornstarch to Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round steak, round
Columns: 75 entries, serving_size to water
dtypes: int64(2), object(73)
memory usage: 5.4+ MB


#### The astype() Method

In [137]:
df = pd.DataFrame({
                   'age':[12,13,14,16],
                   'weight':[41.1,34.5,83.2,90.1],
                   'height':['1.72','1.74','1.91','1.54']
                  })

In [138]:
df

age  weight height
0   12    41.1   1.72
1   13    34.5   1.74
2   14    83.2   1.91
3   16    90.1   1.54

In [139]:
df.height.astype(float)

0    1.72
1    1.74
2    1.91
3    1.54
Name: height, dtype: float64

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     4 non-null      int64  
 1   weight  4 non-null      float64
 2   height  4 non-null      object 
dtypes: float64(1), int64(1), object(1)
memory usage: 224.0+ bytes


In [141]:
df = df.astype(float)

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     4 non-null      float64
 1   weight  4 non-null      float64
 2   height  4 non-null      float64
dtypes: float64(3)
memory usage: 224.0 bytes


In [143]:
df.age.astype(int)

0    12
1    13
2    14
3    16
Name: age, dtype: int32

In [144]:
#OR
df['age'].astype(int)

0    12
1    13
2    14
3    16
Name: age, dtype: int32

In [145]:
#OR
df.astype({'age':int})

age  weight  height
0   12    41.1    1.72
1   13    34.5    1.74
2   14    83.2    1.91
3   16    90.1    1.54

In [146]:
round(df.height, 1)

0    1.7
1    1.7
2    1.9
3    1.5
Name: height, dtype: float64

In [147]:
#nutrition.iloc[:4, :].astype(float)--> this would give an error

#### DataFrame replace() + A glimpse at Regex

In [148]:
dfm = nutrition.iloc[:6, :1]

In [149]:
nutrition.iloc[:4, :1].info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Cornstarch to Teff, uncooked
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   serving_size  4 non-null      object
dtypes: object(1)
memory usage: 64.0+ bytes


In [150]:
dfm.replace(to_replace='100 g', value=100)

serving_size
name                          
Cornstarch                 100
Nuts, pecans               100
Eggplant, raw              100
Teff, uncooked             100
Sherbet, orange            100
Cauliflower, raw           100

In [151]:
dfm.replace(to_replace='100 g', value=100).info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Cornstarch to Cauliflower, raw
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   serving_size  6 non-null      int64
dtypes: int64(1)
memory usage: 96.0+ bytes


In [152]:
#OR
dfm.replace('100 g', 100)

serving_size
name                          
Cornstarch                 100
Nuts, pecans               100
Eggplant, raw              100
Teff, uncooked             100
Sherbet, orange            100
Cauliflower, raw           100

In [153]:
#regex -> regular expressions

In [154]:
dfm.replace('\sg', '', regex=True).astype(int)

serving_size
name                          
Cornstarch                 100
Nuts, pecans               100
Eggplant, raw              100
Teff, uncooked             100
Sherbet, orange            100
Cauliflower, raw           100

In [155]:
nutrition.head(10)

serving_size  calories total_fat saturated_fat cholesterol  \
name                                                                            
Cornstarch                100 g       381      0.1g           NaN           0   
Nuts, pecans              100 g       691       72g          6.2g           0   
Eggplant, raw             100 g        25      0.2g           NaN           0   
Teff, uncooked            100 g       367      2.4g          0.4g           0   
Sherbet, orange           100 g       144        2g          1.2g         1mg   
Cauliflower, raw          100 g        25      0.3g          0.1g           0   
Taro leaves, raw          100 g        42      0.7g          0.2g           0   
Lamb, raw, ground         100 g       282       23g           10g        73mg   
Cheese, camembert         100 g       300       24g           15g        72mg   
Vegetarian fillets        100 g       290       18g          2.8g           0   

                       sodium  choline      folate folic_acid     niacin  ...  \
name                                                                      ...   
Cornstarch            9.00 mg   0.4 mg    0.00 mcg   0.00 mcg   0.000 mg  ...   
Nuts, pecans          0.00 mg  40.5 mg   22.00 mcg   0.00 mcg   1.167 mg  ...   
Eggplant, raw         2.00 mg   6.9 mg   22.00 mcg   0.00 mcg   0.649 mg  ...   
Teff, uncooked       12.00 mg  13.1 mg           0          0   3.363 mg  ...   
Sherbet, orange      46.00 mg   7.7 mg    4.00 mcg   0.00 mcg   0.063 mg  ...   
Cauliflower, raw     30.00 mg  44.3 mg   57.00 mcg   0.00 mcg   0.507 mg  ...   
Taro leaves, raw      3.00 mg  12.8 mg  126.00 mcg   0.00 mcg   1.513 mg  ...   
Lamb, raw, ground    59.00 mg  69.3 mg   18.00 mcg   0.00 mcg   5.960 mg  ...   
Cheese, camembert   842.00 mg  15.4 mg   62.00 mcg   0.00 mcg   0.630 mg  ...   
Vegetarian fillets  490.00 mg  82.0 mg  102.00 mcg   0.00 mcg  12.000 mg  ...   

                        fat saturated_fatty_acids monounsaturated_fatty_acids  \
name                                                                            
Cornstarch           0.05 g               0.009 g                     0.016 g   
Nuts, pecans        71.97 g               6.180 g                    40.801 g   
Eggplant, raw        0.18 g               0.034 g                     0.016 g   
Teff, uncooked       2.38 g               0.449 g                     0.589 g   
Sherbet, orange      2.00 g               1.160 g                     0.530 g   
Cauliflower, raw     0.28 g               0.130 g                     0.034 g   
Taro leaves, raw     0.74 g               0.151 g                     0.060 g   
Lamb, raw, ground   23.41 g              10.190 g                     9.600 g   
Cheese, camembert   24.26 g              15.259 g                     7.023 g   
Vegetarian fillets  18.00 g               2.849 g                     4.376 g   

                   polyunsaturated_fatty_acids fatty_acids_total_trans  \
name                                                                     
Cornstarch                             0.025 g                 0.00 mg   
Nuts, pecans                          21.614 g                 0.00 mg   
Eggplant, raw                          0.076 g                 0.00 mg   
Teff, uncooked                         1.071 g                       0   
Sherbet, orange                        0.080 g                 1.00 mg   
Cauliflower, raw                       0.031 g                 0.00 mg   
Taro leaves, raw                       0.307 g                 0.00 mg   
Lamb, raw, ground                      1.850 g                73.00 mg   
Cheese, camembert                      0.724 g                72.00 mg   
Vegetarian fillets                     9.332 g                 0.00 mg   

                   alcohol     ash caffeine theobromine    water  
name                                                              
Cornstarch           0.0 g  0.09 g  0.00 mg     0.00 mg   8.32 g  
Nuts, peca

### Part I: Collecting The Units

In [156]:
units = nutrition.astype(str).replace('[^a-zA-Z]', '', regex=True) # selecting all the values except the units

In [157]:
units.mode()

serving_size calories total_fat saturated_fat cholesterol sodium choline  \
0            g                  g             g          mg     mg      mg   

  folate folic_acid niacin  ... fat saturated_fatty_acids  \
0    mcg        mcg     mg  ...   g                     g   

  monounsaturated_fatty_acids polyunsaturated_fatty_acids  \
0                           g                           g   

  fatty_acids_total_trans alcohol ash caffeine theobromine water  
0                      mg       g   g       mg          mg     g  

[1 rows x 75 columns]

In [158]:
nutrition.sample(20, axis=1).head()

carotene_beta   sugars threonine folic_acid tyrosine  \
name                                                                   
Cornstarch           0.00 mcg   0.00 g   0.009 g   0.00 mcg  0.010 g   
Nuts, pecans        29.00 mcg   3.97 g   0.306 g   0.00 mcg  0.215 g   
Eggplant, raw       14.00 mcg   3.53 g   0.037 g   0.00 mcg  0.027 g   
Teff, uncooked       5.00 mcg   1.84 g   0.510 g          0  0.458 g   
Sherbet, orange      1.00 mcg  24.32 g         0   0.00 mcg        0   

                cholesterol vitamin_c vitamin_k cryptoxanthin_beta alcohol  \
name                                                                         
Cornstarch                0    0.0 mg   0.0 mcg           0.00 mcg   0.0 g   
Nuts, pecans              0    1.1 mg   3.5 mcg           9.00 mcg   0.0 g   
Eggplant, raw             0    2.2 mg   3.5 mcg           0.00 mcg   0.0 g   
Teff, uncooked            0         0   1.9 mcg           0.00 mcg       0   
Sherbet, orange         1mg    2.3 mg   0.0 mcg           5.00 mcg   0.0 g   

                carotene_alpha  magnesium   serine lutein_zeaxanthin  glycine  \
name                                                                            
Cornstarch            0.00 mcg    3.00 mg  0.012 g          0.00 mcg  0.009 g   
Nuts, pecans          0.00 mcg  121.00 mg  0.474 g         17.00 mcg  0.453 g   
Eggplant, raw         0.00 mcg   14.00 mg  0.042 g         36.00 mcg  0.041 g   
Teff, uncooked        0.00 mcg  184.00 mg  0.622 g         66.00 mcg  0.477 g   
Sherbet, orange       0.00 mcg    8.00 mg        0          7.00 mcg        0   

                serving_size selenium  leucine manganese galactose  
name                                                                
Cornstarch             100 g  2.8 mcg  0.036 g  0.053 mg         0  
Nuts, pecans           100 g  3.8 mcg  0.598 g  4.500 mg         0  
Eggplant, raw          100 g  0.3 mcg  0.064 g  0.232 mg         0  
Teff, uncooked         100 g  4.4 mcg  1.068 g  9.240 mg    0.00 g  
Sherbet, orange        100 g  1.5 mcg        0  0.011 mg         0

In [159]:
units.head()

serving_size calories total_fat saturated_fat cholesterol  \
name                                                                        
Cornstarch                 g                  g           nan               
Nuts, pecans               g                  g             g               
Eggplant, raw              g                  g           nan               
Teff, uncooked             g                  g             g               
Sherbet, orange            g                  g             g          mg   

                sodium choline folate folic_acid niacin  ... fat  \
name                                                     ...       
Cornstarch          mg      mg    mcg        mcg     mg  ...   g   
Nuts, pecans        mg      mg    mcg        mcg     mg  ...   g   
Eggplant, raw       mg      mg    mcg        mcg     mg  ...   g   
Teff, uncooked      mg      mg                       mg  ...   g   
Sherbet, orange     mg      mg    mcg        mcg     mg  ...   g   

                saturated_fatty_acids monounsaturated_fatty_acids  \
name                                                                
Cornstarch                          g                           g   
Nuts, pecans                        g                           g   
Eggplant, raw                       g                           g   
Teff, uncooked                      g                           g   
Sherbet, orange                     g                           g   

                polyunsaturated_fatty_acids fatty_acids_total_trans alcohol  \
name                                                                          
Cornstarch                                g                      mg       g   
Nuts, pecans                              g                      mg       g   
Eggplant, raw                             g                      mg       g   
Teff, uncooked                            g                                   
Sherbet, orange                           g                      mg       g   

                ash caffeine theobromine water  
name                                            
Cornstarch        g       mg          mg     g  
Nuts, pecans      g       mg          mg     g  
Eggplant, raw     g       mg          mg     g  
Teff, uncooked    g                          g  
Sherbet, orange   g       mg          mg     g  

[5 rows x 75 columns]

In [160]:
units.saturated_fat.value_counts()

g      7199
nan    1590
Name: saturated_fat, dtype: int64

In [161]:
#OR
units['saturated_fat'].value_counts()

g      7199
nan    1590
Name: saturated_fat, dtype: int64

In [162]:
units = units.mode()

### The rename() Method

In [163]:
df

age  weight  height
0  12.0    41.1    1.72
1  13.0    34.5    1.74
2  14.0    83.2    1.91
3  16.0    90.1    1.54

In [164]:
df.rename(index={0:'Pikachu'})

age  weight  height
Pikachu  12.0    41.1    1.72
1        13.0    34.5    1.74
2        14.0    83.2    1.91
3        16.0    90.1    1.54

In [165]:
df.rename(columns={'weight':'Weight(kg)'})

age  Weight(kg)  height
0  12.0        41.1    1.72
1  13.0        34.5    1.74
2  14.0        83.2    1.91
3  16.0        90.1    1.54

In [166]:
df.rename(columns={'height':'Height(cm)', 'age':'Age'}, index={0:'a', 1:'b', 2:'c', 3:'d'}) #renaming multiple columns and rows

Age  weight  Height(cm)
a  12.0    41.1        1.72
b  13.0    34.5        1.74
c  14.0    83.2        1.91
d  16.0    90.1        1.54

In [167]:
#rename using mapper
df.rename(mapper={'height':'Height(cm)'}, axis=1)#the only thing is mapper allows only index or column one at a time, not both.

age  weight  Height(cm)
0  12.0    41.1        1.72
1  13.0    34.5        1.74
2  14.0    83.2        1.91
3  16.0    90.1        1.54

#### DataFrame dropna()

In [168]:
#setting rows and columns to nan
df.loc[2, 'weight'] = np.nan 

In [169]:
df

age  weight  height
0  12.0    41.1    1.72
1  13.0    34.5    1.74
2  14.0     NaN    1.91
3  16.0    90.1    1.54

In [170]:
df.loc[1, :] = np.nan

In [171]:
df

age  weight  height
0  12.0    41.1    1.72
1   NaN     NaN     NaN
2  14.0     NaN    1.91
3  16.0    90.1    1.54

In [172]:
df.dropna() # drops all rows with the NaN value

age  weight  height
0  12.0    41.1    1.72
3  16.0    90.1    1.54

In [173]:
# the above cell is also the same as 
df.dropna(how='any', axis=0)

age  weight  height
0  12.0    41.1    1.72
3  16.0    90.1    1.54

In [174]:
df

age  weight  height
0  12.0    41.1    1.72
1   NaN     NaN     NaN
2  14.0     NaN    1.91
3  16.0    90.1    1.54

In [175]:
df.dropna(how='all', axis=0)# drops rows that have only NaN as values

age  weight  height
0  12.0    41.1    1.72
2  14.0     NaN    1.91
3  16.0    90.1    1.54

#### working with thresh

In [176]:
df

age  weight  height
0  12.0    41.1    1.72
1   NaN     NaN     NaN
2  14.0     NaN    1.91
3  16.0    90.1    1.54

In [177]:
df.dropna(thresh=3, axis=0)

age  weight  height
0  12.0    41.1    1.72
3  16.0    90.1    1.54

In [178]:
df.shape

(4, 3)

In [179]:
df.dropna(thresh=df.shape[1], axis=0)

age  weight  height
0  12.0    41.1    1.72
3  16.0    90.1    1.54

In [180]:
df

age  weight  height
0  12.0    41.1    1.72
1   NaN     NaN     NaN
2  14.0     NaN    1.91
3  16.0    90.1    1.54

In [181]:
df.dropna(axis=1) #drops any column that has NaN value

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [182]:
df.dropna(axis=1, how='all')# it should drop columns that has all of its values to be NaN that's why nothing changed

age  weight  height
0  12.0    41.1    1.72
1   NaN     NaN     NaN
2  14.0     NaN    1.91
3  16.0    90.1    1.54

In [183]:
df.dropna(thresh=3, axis=1, inplace=True)#thresh drops specified axis that doesn't have upt to specified non-NaN values

In [184]:
df.dropna(thresh=2, axis=1)#this should drop nothing

age  height
0  12.0    1.72
1   NaN     NaN
2  14.0    1.91
3  16.0    1.54

#### dropna() with subset

In [185]:
df

age  height
0  12.0    1.72
1   NaN     NaN
2  14.0    1.91
3  16.0    1.54

In [186]:
#adding a column
df['gender'] = ['M', 'F', np.nan, 'F']

In [187]:
df

age  height gender
0  12.0    1.72      M
1   NaN     NaN      F
2  14.0    1.91    NaN
3  16.0    1.54      F

In [188]:
#the subset parameter
df.dropna(axis=0, how='any', subset=['gender'])#this removes NaN in the column specified in the subset based on the axis

age  height gender
0  12.0    1.72      M
1   NaN     NaN      F
3  16.0    1.54      F

In [189]:
df

age  height gender
0  12.0    1.72      M
1   NaN     NaN      F
2  14.0    1.91    NaN
3  16.0    1.54      F

In [190]:
df.dropna(axis=1, how='any', subset=[0,1])

gender
0      M
1      F
2    NaN
3      F

### Part II: Merging Units with Column Names

In [191]:
#Detour-> Dataframe iteration

In [192]:
units = units.mode()

In [193]:
units

serving_size calories total_fat saturated_fat cholesterol sodium choline  \
0            g                  g             g          mg     mg      mg   

  folate folic_acid niacin  ... fat saturated_fatty_acids  \
0    mcg        mcg     mg  ...   g                     g   

  monounsaturated_fatty_acids polyunsaturated_fatty_acids  \
0                           g                           g   

  fatty_acids_total_trans alcohol ash caffeine theobromine water  
0                      mg       g   g       mg          mg     g  

[1 rows x 75 columns]

In [194]:
for k in units:
    print(k)

serving_size
calories
total_fat
saturated_fat
cholesterol
sodium
choline
folate
folic_acid
niacin
pantothenic_acid
riboflavin
thiamin
vitamin_a
vitamin_a_rae
carotene_alpha
carotene_beta
cryptoxanthin_beta
lutein_zeaxanthin
lucopene
vitamin_b12
vitamin_b6
vitamin_c
vitamin_d
vitamin_e
tocopherol_alpha
vitamin_k
calcium
copper
irom
magnesium
manganese
phosphorous
potassium
selenium
zink
protein
alanine
arginine
aspartic_acid
cystine
glutamic_acid
glycine
histidine
hydroxyproline
isoleucine
leucine
lysine
methionine
phenylalanine
proline
serine
threonine
tryptophan
tyrosine
valine
carbohydrate
fiber
sugars
fructose
galactose
glucose
lactose
maltose
sucrose
fat
saturated_fatty_acids
monounsaturated_fatty_acids
polyunsaturated_fatty_acids
fatty_acids_total_trans
alcohol
ash
caffeine
theobromine
water


In [195]:
for k in units:
    print(k,units[k].iat[0])

serving_size g
calories 
total_fat g
saturated_fat g
cholesterol mg
sodium mg
choline mg
folate mcg
folic_acid mcg
niacin mg
pantothenic_acid mg
riboflavin mg
thiamin mg
vitamin_a IU
vitamin_a_rae mcg
carotene_alpha mcg
carotene_beta mcg
cryptoxanthin_beta mcg
lutein_zeaxanthin mcg
lucopene 
vitamin_b12 mcg
vitamin_b6 mg
vitamin_c mg
vitamin_d IU
vitamin_e mg
tocopherol_alpha mg
vitamin_k mcg
calcium mg
copper mg
irom mg
magnesium mg
manganese mg
phosphorous mg
potassium mg
selenium mcg
zink mg
protein g
alanine g
arginine g
aspartic_acid g
cystine g
glutamic_acid g
glycine g
histidine g
hydroxyproline 
isoleucine g
leucine g
lysine g
methionine g
phenylalanine g
proline g
serine g
threonine g
tryptophan g
tyrosine g
valine g
carbohydrate g
fiber g
sugars g
fructose 
galactose 
glucose 
lactose 
maltose 
sucrose 
fat g
saturated_fatty_acids g
monounsaturated_fatty_acids g
polyunsaturated_fatty_acids g
fatty_acids_total_trans mg
alcohol g
ash g
caffeine mg
theobromine mg
water g


In [196]:
for k in units:
    print(units[k].iat[0])

g

g
g
mg
mg
mg
mcg
mcg
mg
mg
mg
mg
IU
mcg
mcg
mcg
mcg
mcg

mcg
mg
mg
IU
mg
mg
mcg
mg
mg
mg
mg
mg
mg
mg
mcg
mg
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g
g
g






g
g
g
g
mg
g
g
mg
mg
g


In [197]:
#droping columns that do not have units

In [198]:
units = units.replace('', np.nan).dropna(axis=1)

In [199]:
for k in units:
    print(units[k].iat[0])

g
g
g
mg
mg
mg
mcg
mcg
mg
mg
mg
mg
IU
mcg
mcg
mcg
mcg
mcg
mcg
mg
mg
IU
mg
mg
mcg
mg
mg
mg
mg
mg
mg
mg
mcg
mg
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
mg
g
g
mg
mg
g


In [200]:
mapper = {k:k + '_' + units[k].iat[0] for k in units}

In [201]:
mapper

{'serving_size': 'serving_size_g',
 'total_fat': 'total_fat_g',
 'saturated_fat': 'saturated_fat_g',
 'cholesterol': 'cholesterol_mg',
 'sodium': 'sodium_mg',
 'choline': 'choline_mg',
 'folate': 'folate_mcg',
 'folic_acid': 'folic_acid_mcg',
 'niacin': 'niacin_mg',
 'pantothenic_acid': 'pantothenic_acid_mg',
 'riboflavin': 'riboflavin_mg',
 'thiamin': 'thiamin_mg',
 'vitamin_a': 'vitamin_a_IU',
 'vitamin_a_rae': 'vitamin_a_rae_mcg',
 'carotene_alpha': 'carotene_alpha_mcg',
 'carotene_beta': 'carotene_beta_mcg',
 'cryptoxanthin_beta': 'cryptoxanthin_beta_mcg',
 'lutein_zeaxanthin': 'lutein_zeaxanthin_mcg',
 'vitamin_b12': 'vitamin_b12_mcg',
 'vitamin_b6': 'vitamin_b6_mg',
 'vitamin_c': 'vitamin_c_mg',
 'vitamin_d': 'vitamin_d_IU',
 'vitamin_e': 'vitamin_e_mg',
 'tocopherol_alpha': 'tocopherol_alpha_mg',
 'vitamin_k': 'vitamin_k_mcg',
 'calcium': 'calcium_mg',
 'copper': 'copper_mg',
 'irom': 'irom_mg',
 'magnesium': 'magnesium_mg',
 'manganese': 'manganese_mg',
 'phosphorous': 'phospho

In [202]:
nutrition.rename(columns=mapper, inplace=True)

In [203]:
nutrition.head()

serving_size_g  calories total_fat_g saturated_fat_g  \
name                                                                   
Cornstarch               100 g       381        0.1g             NaN   
Nuts, pecans             100 g       691         72g            6.2g   
Eggplant, raw            100 g        25        0.2g             NaN   
Teff, uncooked           100 g       367        2.4g            0.4g   
Sherbet, orange          100 g       144          2g            1.2g   

                cholesterol_mg sodium_mg choline_mg folate_mcg folic_acid_mcg  \
name                                                                            
Cornstarch                   0   9.00 mg     0.4 mg   0.00 mcg       0.00 mcg   
Nuts, pecans                 0   0.00 mg    40.5 mg  22.00 mcg       0.00 mcg   
Eggplant, raw                0   2.00 mg     6.9 mg  22.00 mcg       0.00 mcg   
Teff, uncooked               0  12.00 mg    13.1 mg          0              0   
Sherbet, orange            1mg  46.00 mg     7.7 mg   4.00 mcg       0.00 mcg   

                niacin_mg  ...    fat_g saturated_fatty_acids_g  \
name                       ...                                    
Cornstarch       0.000 mg  ...   0.05 g                 0.009 g   
Nuts, pecans     1.167 mg  ...  71.97 g                 6.180 g   
Eggplant, raw    0.649 mg  ...   0.18 g                 0.034 g   
Teff, uncooked   3.363 mg  ...   2.38 g                 0.449 g   
Sherbet, orange  0.063 mg  ...   2.00 g                 1.160 g   

                monounsaturated_fatty_acids_g polyunsaturated_fatty_acids_g  \
name                                                                          
Cornstarch                            0.016 g                       0.025 g   
Nuts, pecans                         40.801 g                      21.614 g   
Eggplant, raw                         0.016 g                       0.076 g   
Teff, uncooked                        0.589 g                       1.071 g   
Sherbet, orange                       0.530 g                       0.080 g   

                fatty_acids_total_trans_mg alcohol_g   ash_g caffeine_mg  \
name                                                                       
Cornstarch                         0.00 mg     0.0 g  0.09 g     0.00 mg   
Nuts, pecans                       0.00 mg     0.0 g  1.49 g     0.00 mg   
Eggplant, raw                      0.00 mg     0.0 g  0.66 g     0.00 mg   
Teff, uncooked                           0         0  2.37 g           0   
Sherbet, orange                    1.00 mg     0.0 g  0.40 g     0.00 mg   

                theobromine_mg  water_g  
name                                     
Cornstarch             0.00 mg   8.32 g  
Nuts, pecans           0.00 mg   3.52 g  
Eggplant, raw          0.00 mg  92.30 g  
Teff, uncooked               0   8.82 g  
Sherbet, orange        0.00 mg  66.10 g  

[5 rows x 75 columns]

#### Removing the units from the values

In [204]:
nutrition.replace('[a-zA-Z]', '', regex=True, inplace=True)

In [205]:
nutrition.dtypes

serving_size_g     object
calories            int64
total_fat_g        object
saturated_fat_g    object
cholesterol_mg     object
                    ...  
alcohol_g          object
ash_g              object
caffeine_mg        object
theobromine_mg     object
water_g            object
Length: 75, dtype: object

In [206]:
nutrition.dtypes.value_counts()

object    73
int64      2
dtype: int64

In [207]:
nutrition = nutrition.astype(float)

In [208]:
nutrition.dtypes

serving_size_g     float64
calories           float64
total_fat_g        float64
saturated_fat_g    float64
cholesterol_mg     float64
                    ...   
alcohol_g          float64
ash_g              float64
caffeine_mg        float64
theobromine_mg     float64
water_g            float64
Length: 75, dtype: object

In [209]:
nutrition.dtypes.value_counts()

float64    75
dtype: int64

In [210]:
nutrition.info(memory_usage='deep', verbose=False)

<class 'pandas.core.frame.DataFrame'>
Index: 8789 entries, Cornstarch to Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round steak, round
Columns: 75 entries, serving_size_g to water_g
dtypes: float64(75)
memory usage: 6.0 MB


#### Filtering in 2D

In [211]:
nutrition.filter(like='octopus', axis=0)

serving_size_g  calories  \
name                                                                      
Mollusks, raw, common, octopus                          100.0      82.0   
Mollusks, moist heat, cooked, common, octopus           100.0     164.0   

                                               total_fat_g  saturated_fat_g  \
name                                                                          
Mollusks, raw, common, octopus                         1.0              0.2   
Mollusks, moist heat, cooked, common, octopus          2.1              0.5   

                                               cholesterol_mg  sodium_mg  \
name                                                                       
Mollusks, raw, common, octopus                           48.0      230.0   
Mollusks, moist heat, cooked, common, octopus            96.0      460.0   

                                               choline_mg  folate_mcg  \
name                                                                    
Mollusks, raw, common, octopus                       65.0        16.0   
Mollusks, moist heat, cooked, common, octopus        81.0        24.0   

                                               folic_acid_mcg  niacin_mg  ...  \
name                                                                      ...   
Mollusks, raw, common, octopus                            0.0       2.10  ...   
Mollusks, moist heat, cooked, common, octopus             0.0       3.78  ...   

                                               fat_g  saturated_fatty_acids_g  \
name                                                                            
Mollusks, raw, common, octopus                  1.04                    0.227   
Mollusks, moist heat, cooked, common, octopus   2.08                    0.453   

                                               monounsaturated_fatty_acids_g  \
name                                                                           
Mollusks, raw, common, octopus                                         0.162   
Mollusks, moist heat, cooked, common, octopus                          0.324   

                                               polyunsaturated_fatty_acids_g  \
name                                                                           
Mollusks, raw, common, octopus                                         0.239   
Mollusks, moist heat, cooked, common, octopus                          0.477   

                                               fatty_acids_total_trans_mg  \
name                                                                        
Mollusks, raw, common, octopus                                       48.0   
Mollusks, moist heat, cooked, common, octopus                        96.0   

                                               alcohol_g  ash_g  caffeine_mg  \
name                                                                           
Mollusks, raw, common, octopus                       0.0    1.6          0.0   
Mollusks, moist heat, cooked, common, octopus        0.0    3.2          0.0   

                                               theobromine_mg  water_g  
name                                                                    
Mollusks, raw, common, octopus                            0.0    80.25  
Mollusks, moist heat, cooked, common, octopus             0.0    60.50  

[2 rows x 75 columns]

In [212]:
nutrition.filter(regex='octopus', axis=0)

serving_size_g  calories  \
name                                                                      
Mollusks, raw, common, octopus                          100.0      82.0   
Mollusks, moist heat, cooked, common, octopus           100.0     164.0   

                                               total_fat_g  saturated_fat_g  \
name                                                                          
Mollusks, raw, common, octopus                         1.0              0.2   
Mollusks, moist heat, cooked, common, octopus          2.1              0.5   

                                               cholesterol_mg  sodium_mg  \
name                                                                       
Mollusks, raw, common, octopus                           48.0      230.0   
Mollusks, moist heat, cooked, common, octopus            96.0      460.0   

                                               choline_mg  folate_mcg  \
name                                                                    
Mollusks, raw, common, octopus                       65.0        16.0   
Mollusks, moist heat, cooked, common, octopus        81.0        24.0   

                                               folic_acid_mcg  niacin_mg  ...  \
name                                                                      ...   
Mollusks, raw, common, octopus                            0.0       2.10  ...   
Mollusks, moist heat, cooked, common, octopus             0.0       3.78  ...   

                                               fat_g  saturated_fatty_acids_g  \
name                                                                            
Mollusks, raw, common, octopus                  1.04                    0.227   
Mollusks, moist heat, cooked, common, octopus   2.08                    0.453   

                                               monounsaturated_fatty_acids_g  \
name                                                                           
Mollusks, raw, common, octopus                                         0.162   
Mollusks, moist heat, cooked, common, octopus                          0.324   

                                               polyunsaturated_fatty_acids_g  \
name                                                                           
Mollusks, raw, common, octopus                                         0.239   
Mollusks, moist heat, cooked, common, octopus                          0.477   

                                               fatty_acids_total_trans_mg  \
name                                                                        
Mollusks, raw, common, octopus                                       48.0   
Mollusks, moist heat, cooked, common, octopus                        96.0   

                                               alcohol_g  ash_g  caffeine_mg  \
name                                                                           
Mollusks, raw, common, octopus                       0.0    1.6          0.0   
Mollusks, moist heat, cooked, common, octopus        0.0    3.2          0.0   

                                               theobromine_mg  water_g  
name                                                                    
Mollusks, raw, common, octopus                            0.0    80.25  
Mollusks, moist heat, cooked, common, octopus             0.0    60.50  

[2 rows x 75 columns]

In [213]:
nutrition.filter(regex='Octopus', axis=0)

serving_size_g  calories  total_fat_g  \
name                                                             
Octopus (Alaska Native)           100.0      56.0          0.8   

                         saturated_fat_g  cholesterol_mg  sodium_mg  \
name                                                                  
Octopus (Alaska Native)              0.2            41.0        0.0   

                         choline_mg  folate_mcg  folic_acid_mcg  niacin_mg  \
name                                                                         
Octopus (Alaska Native)         0.0         0.0             0.0        2.0   

                         ...  fat_g  saturated_fatty_acids_g  \
name                     ...                                   
Octopus (Alaska Native)  ...    0.8                      0.2   

                         monounsaturated_fatty_acids_g  \
name                                                     
Octopus (Alaska Native)                            0.0   

                         polyunsaturated_fatty_acids_g  \
name                                                     
Octopus (Alaska Native)                            0.2   

                         fatty_acids_total_trans_mg  alcohol_g  ash_g  \
name                                                                    
Octopus (Alaska Native)                        41.0        0.0    1.5   

                         caffeine_mg  theobromine_mg  water_g  
name                                                           
Octopus (Alaska Native)          0.0             0.0     84.0  

[1 rows x 75 columns]

In [214]:
nutrition.filter(regex='[Oo]ctopus', axis=0)

serving_size_g  calories  \
name                                                                      
Octopus (Alaska Native)                                 100.0      56.0   
Mollusks, raw, common, octopus                          100.0      82.0   
Mollusks, moist heat, cooked, common, octopus           100.0     164.0   

                                               total_fat_g  saturated_fat_g  \
name                                                                          
Octopus (Alaska Native)                                0.8              0.2   
Mollusks, raw, common, octopus                         1.0              0.2   
Mollusks, moist heat, cooked, common, octopus          2.1              0.5   

                                               cholesterol_mg  sodium_mg  \
name                                                                       
Octopus (Alaska Native)                                  41.0        0.0   
Mollusks, raw, common, octopus                           48.0      230.0   
Mollusks, moist heat, cooked, common, octopus            96.0      460.0   

                                               choline_mg  folate_mcg  \
name                                                                    
Octopus (Alaska Native)                               0.0         0.0   
Mollusks, raw, common, octopus                       65.0        16.0   
Mollusks, moist heat, cooked, common, octopus        81.0        24.0   

                                               folic_acid_mcg  niacin_mg  ...  \
name                                                                      ...   
Octopus (Alaska Native)                                   0.0       2.00  ...   
Mollusks, raw, common, octopus                            0.0       2.10  ...   
Mollusks, moist heat, cooked, common, octopus             0.0       3.78  ...   

                                               fat_g  saturated_fatty_acids_g  \
name                                                                            
Octopus (Alaska Native)                         0.80                    0.200   
Mollusks, raw, common, octopus                  1.04                    0.227   
Mollusks, moist heat, cooked, common, octopus   2.08                    0.453   

                                               monounsaturated_fatty_acids_g  \
name                                                                           
Octopus (Alaska Native)                                                0.000   
Mollusks, raw, common, octopus                                         0.162   
Mollusks, moist heat, cooked, common, octopus                          0.324   

                                               polyunsaturated_fatty_acids_g  \
name                                                                           
Octopus (Alaska Native)                                                0.200   
Mollusks, raw, common, octopus                                         0.239   
Mollusks, moist heat, cooked, common, octopus                          0.477   

                                               fatty_acids_total_trans_mg  \
name                                                                        
Octopus (Alaska Native)                                              41.0   
Mollusks, raw, common, octopus                                       48.0   
Mollusks, moist heat, cooked, common, octopus                        96.0   

                                               alcohol_g  ash_g  caffeine_mg  \
name                                                                           
Octopus (Alaska Native)                              0.0    1.5          0.0   
Mollusks, raw, common, octopus                       0.0    1.6          0.0   
Mollusks, moist heat, cooked, common, octopus        0.0    3.2          0.0   

                                               theobromine_mg  water_g  
name                                                  

In [215]:
nutrition.filter(regex='(?i)octopus', axis=0)

serving_size_g  calories  \
name                                                                      
Octopus (Alaska Native)                                 100.0      56.0   
Mollusks, raw, common, octopus                          100.0      82.0   
Mollusks, moist heat, cooked, common, octopus           100.0     164.0   

                                               total_fat_g  saturated_fat_g  \
name                                                                          
Octopus (Alaska Native)                                0.8              0.2   
Mollusks, raw, common, octopus                         1.0              0.2   
Mollusks, moist heat, cooked, common, octopus          2.1              0.5   

                                               cholesterol_mg  sodium_mg  \
name                                                                       
Octopus (Alaska Native)                                  41.0        0.0   
Mollusks, raw, common, octopus                           48.0      230.0   
Mollusks, moist heat, cooked, common, octopus            96.0      460.0   

                                               choline_mg  folate_mcg  \
name                                                                    
Octopus (Alaska Native)                               0.0         0.0   
Mollusks, raw, common, octopus                       65.0        16.0   
Mollusks, moist heat, cooked, common, octopus        81.0        24.0   

                                               folic_acid_mcg  niacin_mg  ...  \
name                                                                      ...   
Octopus (Alaska Native)                                   0.0       2.00  ...   
Mollusks, raw, common, octopus                            0.0       2.10  ...   
Mollusks, moist heat, cooked, common, octopus             0.0       3.78  ...   

                                               fat_g  saturated_fatty_acids_g  \
name                                                                            
Octopus (Alaska Native)                         0.80                    0.200   
Mollusks, raw, common, octopus                  1.04                    0.227   
Mollusks, moist heat, cooked, common, octopus   2.08                    0.453   

                                               monounsaturated_fatty_acids_g  \
name                                                                           
Octopus (Alaska Native)                                                0.000   
Mollusks, raw, common, octopus                                         0.162   
Mollusks, moist heat, cooked, common, octopus                          0.324   

                                               polyunsaturated_fatty_acids_g  \
name                                                                           
Octopus (Alaska Native)                                                0.200   
Mollusks, raw, common, octopus                                         0.239   
Mollusks, moist heat, cooked, common, octopus                          0.477   

                                               fatty_acids_total_trans_mg  \
name                                                                        
Octopus (Alaska Native)                                              41.0   
Mollusks, raw, common, octopus                                       48.0   
Mollusks, moist heat, cooked, common, octopus                        96.0   

                                               alcohol_g  ash_g  caffeine_mg  \
name                                                                           
Octopus (Alaska Native)                              0.0    1.5          0.0   
Mollusks, raw, common, octopus                       0.0    1.6          0.0   
Mollusks, moist heat, cooked, common, octopus        0.0    3.2          0.0   

                                               theobromine_mg  water_g  
name                                                  

In [216]:
#filtering both dimensions
nutrition.filter(regex='(?i)octopus', axis=0)\
         .filter(items=['cholesterol_mg', 'total_fat_g', 'saturated_fat_g'])

cholesterol_mg  total_fat_g  \
name                                                                         
Octopus (Alaska Native)                                  41.0          0.8   
Mollusks, raw, common, octopus                           48.0          1.0   
Mollusks, moist heat, cooked, common, octopus            96.0          2.1   

                                               saturated_fat_g  
name                                                            
Octopus (Alaska Native)                                    0.2  
Mollusks, raw, common, octopus                             0.2  
Mollusks, moist heat, cooked, common, octopus              0.5

In [217]:
nutrition.filter(regex='(?i)octopus', axis=0)\
         .loc[:, ['cholesterol_mg', 'total_fat_g', 'saturated_fat_g']]

cholesterol_mg  total_fat_g  \
name                                                                         
Octopus (Alaska Native)                                  41.0          0.8   
Mollusks, raw, common, octopus                           48.0          1.0   
Mollusks, moist heat, cooked, common, octopus            96.0          2.1   

                                               saturated_fat_g  
name                                                            
Octopus (Alaska Native)                                    0.2  
Mollusks, raw, common, octopus                             0.2  
Mollusks, moist heat, cooked, common, octopus              0.5

#### DataFrame Sorting

In [218]:
nutrition.head(4)

serving_size_g  calories  total_fat_g  saturated_fat_g  \
name                                                                     
Cornstarch               100.0     381.0          0.1              NaN   
Nuts, pecans             100.0     691.0         72.0              6.2   
Eggplant, raw            100.0      25.0          0.2              NaN   
Teff, uncooked           100.0     367.0          2.4              0.4   

                cholesterol_mg  sodium_mg  choline_mg  folate_mcg  \
name                                                                
Cornstarch                 0.0        9.0         0.4         0.0   
Nuts, pecans               0.0        0.0        40.5        22.0   
Eggplant, raw              0.0        2.0         6.9        22.0   
Teff, uncooked             0.0       12.0        13.1         0.0   

                folic_acid_mcg  niacin_mg  ...  fat_g  \
name                                       ...          
Cornstarch                 0.0      0.000  ...   0.05   
Nuts, pecans               0.0      1.167  ...  71.97   
Eggplant, raw              0.0      0.649  ...   0.18   
Teff, uncooked             0.0      3.363  ...   2.38   

                saturated_fatty_acids_g  monounsaturated_fatty_acids_g  \
name                                                                     
Cornstarch                        0.009                          0.016   
Nuts, pecans                      6.180                         40.801   
Eggplant, raw                     0.034                          0.016   
Teff, uncooked                    0.449                          0.589   

                polyunsaturated_fatty_acids_g  fatty_acids_total_trans_mg  \
name                                                                        
Cornstarch                              0.025                         0.0   
Nuts, pecans                           21.614                         0.0   
Eggplant, raw                           0.076                         0.0   
Teff, uncooked                          1.071                         0.0   

                alcohol_g  ash_g  caffeine_mg  theobromine_mg  water_g  
name                                                                    
Cornstarch            0.0   0.09          0.0             0.0     8.32  
Nuts, pecans          0.0   1.49          0.0             0.0     3.52  
Eggplant, raw         0.0   0.66          0.0             0.0    92.30  
Teff, uncooked        0.0   2.37          0.0             0.0     8.82  

[4 rows x 75 columns]

In [219]:
nutrition.vitamin_b12_mcg

name
Cornstarch                                                                                            0.00
Nuts, pecans                                                                                          0.00
Eggplant, raw                                                                                         0.00
Teff, uncooked                                                                                        0.00
Sherbet, orange                                                                                       0.13
                                                                                                      ... 
Beef, raw, all grades, trimmed to 0" fat, separable lean and fat, boneless, top round roast, round    1.64
Lamb, cooked, separable lean only, composite of trimmed retail cuts, frozen, imported, New Zealand    2.95
Lamb, raw, separable lean and fat, composite of trimmed retail cuts, frozen, imported, New Zealand    2.42
Beef, raw, all grades, trimmed t

In [220]:
nutrition.filter(like='vitamin_b12')

vitamin_b12_mcg
name                                                               
Cornstarch                                                     0.00
Nuts, pecans                                                   0.00
Eggplant, raw                                                  0.00
Teff, uncooked                                                 0.00
Sherbet, orange                                                0.13
...                                                             ...
Beef, raw, all grades, trimmed to 0" fat, separ...             1.64
Lamb, cooked, separable lean only, composite of...             2.95
Lamb, raw, separable lean and fat, composite of...             2.42
Beef, raw, all grades, trimmed to 0" fat, separ...             1.84
Beef, raw, all grades, trimmed to 0" fat, separ...             1.84

[8789 rows x 1 columns]

In [221]:
nutrition.vitamin_b12_mcg.sort_values(ascending=False)

name
Mollusks, moist heat, cooked, mixed species, clam                                   98.89
Beef, boiled, cooked, variety meats and by-products liver, imported, New Zealand    96.00
Lamb, raw, liver, variety meats and by-products                                     90.05
Lamb, pan-fried, cooked, liver, variety meats and by-products                       85.70
Veal, braised, cooked, liver, variety meats and by-products                         84.60
                                                                                    ...  
Mothbeans, without salt, boiled, cooked, mature seeds                                0.00
Tomato products, with herbs and cheese, sauce, canned                                0.00
Cocoa, processed with alkali, unsweetened, dry powder                                0.00
Apricots, stewed, sulfured, dehydrated (low-moisture)                                0.00
Cornstarch                                                                           0.00
Name:

In [222]:
nutrition.sort_values(by=['calories'], ascending=False)

serving_size_g  calories  \
name                                                                           
Fat, mutton tallow                                           100.0     902.0   
Fish oil, salmon                                             100.0     902.0   
Lard                                                         100.0     902.0   
Fat, beef tallow                                             100.0     902.0   
Fish oil, cod liver                                          100.0     902.0   
...                                                            ...       ...   
Beverages, decaffeinated, brewed, green, tea                 100.0       0.0   
Beverages, caffeine free, cola, ZEVIA                        100.0       0.0   
Carbonated beverage, without caffeine, with sod...           100.0       0.0   
Beverages, unsweetened, ready to drink, green, tea           100.0       0.0   
Salt, table                                                  100.0       0.0   

                                                    total_fat_g  \
name                                                              
Fat, mutton tallow                                        100.0   
Fish oil, salmon                                          100.0   
Lard                                                      100.0   
Fat, beef tallow                                          100.0   
Fish oil, cod liver                                       100.0   
...                                                         ...   
Beverages, decaffeinated, brewed, green, tea                0.0   
Beverages, caffeine free, cola, ZEVIA                       0.0   
Carbonated beverage, without caffeine, with sod...          0.0   
Beverages, unsweetened, ready to drink, green, tea          0.0   
Salt, table                                                 0.0   

                                                    saturated_fat_g  \
name                                                                  
Fat, mutton tallow                                             47.0   
Fish oil, salmon                                               20.0   
Lard                                                           39.0   
Fat, beef tallow                                               50.0   
Fish oil, cod liver                                            23.0   
...                                                             ...   
Beverages, decaffeinated, brewed, green, tea                    NaN   
Beverages, caffeine free, cola, ZEVIA                           NaN   
Carbonated beverage, without caffeine, with sod...              NaN   
Beverages, unsweetened, ready to drink, green, tea              NaN   
Salt, table                                                     NaN   

                                                    cholesterol_mg  sodium_mg  \
name                                                                            
Fat, mutton tallow                                           102.0        0.0   
Fish oil, salmon                                             485.0        0.0   
Lard                                                          95.0        0.0   
Fat, beef tallow                                             109.0        0.0   
Fish oil, cod liver                                          570.0        0.0   
...                                                            ...        ...   
Beverages, decaffeinated, brewed, green, tea                   0.0        0.0   
Beverages, caffeine free, cola, ZEVIA                          0.0        6.0   
Carbonated beverage, without caffeine, with sod...             0.0       16.0   
Beverages, unsweetened, ready to drink, green, tea             0.0        7.0   
Salt, table                                                    0.0    38758.0   

                                                    choline_mg  folate_mcg  \
name                                                                         
Fat, 

In [223]:
nutrition.sort_values(by=['cholesterol_mg', 'sodium_mg'], ascending=False)

serving_size_g  calories  \
name                                                                           
Veal, braised, cooked, brain, variety meats and...           100.0     136.0   
Beef, simmered, cooked, brain, variety meats an...           100.0     151.0   
Beef, raw, brain, variety meats and by-products              100.0     143.0   
Lamb, soaked and fried, cooked, brains, importe...           100.0     154.0   
Pork, braised, cooked, brain, variety meats and...           100.0     138.0   
...                                                            ...       ...   
Oil, principal uses icings and fillings, palm, ...           100.0     884.0   
Oil, pourable clear fry, soy (partially hydroge...           100.0     884.0   
Beverages, fortified, Revive Fruit Punch, Glace...           100.0       0.0   
Oil, principal use as a tortilla shortening, so...           100.0     884.0   
Pan Dulce, contains wheat flour and rice flour,...           100.0     445.0   

                                                    total_fat_g  \
name                                                              
Veal, braised, cooked, brain, variety meats and...          9.6   
Beef, simmered, cooked, brain, variety meats an...         11.0   
Beef, raw, brain, variety meats and by-products            10.0   
Lamb, soaked and fried, cooked, brains, importe...         11.0   
Pork, braised, cooked, brain, variety meats and...          9.5   
...                                                         ...   
Oil, principal uses icings and fillings, palm, ...        100.0   
Oil, pourable clear fry, soy (partially hydroge...        100.0   
Beverages, fortified, Revive Fruit Punch, Glace...          0.0   
Oil, principal use as a tortilla shortening, so...        100.0   
Pan Dulce, contains wheat flour and rice flour,...         16.0   

                                                    saturated_fat_g  \
name                                                                  
Veal, braised, cooked, brain, variety meats and...              2.2   
Beef, simmered, cooked, brain, variety meats an...              2.4   
Beef, raw, brain, variety meats and by-products                 2.3   
Lamb, soaked and fried, cooked, brains, importe...              1.4   
Pork, braised, cooked, brain, variety meats and...              2.2   
...                                                             ...   
Oil, principal uses icings and fillings, palm, ...             28.0   
Oil, pourable clear fry, soy (partially hydroge...             15.0   
Beverages, fortified, Revive Fruit Punch, Glace...              NaN   
Oil, principal use as a tortilla shortening, so...             26.0   
Pan Dulce, contains wheat flour and rice flour,...              NaN   

                                                    cholesterol_mg  sodium_mg  \
name                                                                            
Veal, braised, cooked, brain, variety meats and...          3100.0      156.0   
Beef, simmered, cooked, brain, variety meats an...          3100.0      108.0   
Beef, raw, brain, variety meats and by-products             3010.0      126.0   
Lamb, soaked and fried, cooked, brains, importe...          2559.0      101.0   
Pork, braised, cooked, brain, variety meats and...          2552.0       91.0   
...                                                            ...        ...   
Oil, principal uses icings and fillings, palm, ...             0.0        0.0   
Oil, pourable clear fry, soy (partially hydroge...             0.0        0.0   
Beverages, fortified, Revive Fruit Punch, Glace...             0.0        0.0   
Oil, principal use as a tortilla shortening, so...             0.0        0.0   
Pan Dulce, contains wheat flour and rice flour,...             0.0        0.0   

                                                    choline_mg  folate_mcg  \
name                                                                         
Veal,

In [224]:
nutrition.sort_values(by=['cholesterol_mg', 'sodium_mg'], ascending=[False, True])

serving_size_g  calories  \
name                                                                           
Beef, simmered, cooked, brain, variety meats an...           100.0     151.0   
Veal, braised, cooked, brain, variety meats and...           100.0     136.0   
Beef, raw, brain, variety meats and by-products              100.0     143.0   
Lamb, soaked and fried, cooked, brains, importe...           100.0     154.0   
Pork, braised, cooked, brain, variety meats and...           100.0     138.0   
...                                                            ...       ...   
Leavening agents, sodium aluminum sulfate, doub...           100.0      53.0   
Seasoning mix, coriander & annatto, sazon, dry               100.0       0.0   
Desserts, unsweetened, tablets, rennin                       100.0      84.0   
Leavening agents, baking soda                                100.0       0.0   
Salt, table                                                  100.0       0.0   

                                                    total_fat_g  \
name                                                              
Beef, simmered, cooked, brain, variety meats an...         11.0   
Veal, braised, cooked, brain, variety meats and...          9.6   
Beef, raw, brain, variety meats and by-products            10.0   
Lamb, soaked and fried, cooked, brains, importe...         11.0   
Pork, braised, cooked, brain, variety meats and...          9.5   
...                                                         ...   
Leavening agents, sodium aluminum sulfate, doub...          0.0   
Seasoning mix, coriander & annatto, sazon, dry              0.0   
Desserts, unsweetened, tablets, rennin                      0.1   
Leavening agents, baking soda                               0.0   
Salt, table                                                 0.0   

                                                    saturated_fat_g  \
name                                                                  
Beef, simmered, cooked, brain, variety meats an...              2.4   
Veal, braised, cooked, brain, variety meats and...              2.2   
Beef, raw, brain, variety meats and by-products                 2.3   
Lamb, soaked and fried, cooked, brains, importe...              1.4   
Pork, braised, cooked, brain, variety meats and...              2.2   
...                                                             ...   
Leavening agents, sodium aluminum sulfate, doub...              NaN   
Seasoning mix, coriander & annatto, sazon, dry                  NaN   
Desserts, unsweetened, tablets, rennin                          NaN   
Leavening agents, baking soda                                   NaN   
Salt, table                                                     NaN   

                                                    cholesterol_mg  sodium_mg  \
name                                                                            
Beef, simmered, cooked, brain, variety meats an...          3100.0      108.0   
Veal, braised, cooked, brain, variety meats and...          3100.0      156.0   
Beef, raw, brain, variety meats and by-products             3010.0      126.0   
Lamb, soaked and fried, cooked, brains, importe...          2559.0      101.0   
Pork, braised, cooked, brain, variety meats and...          2552.0       91.0   
...                                                            ...        ...   
Leavening agents, sodium aluminum sulfate, doub...             0.0    10600.0   
Seasoning mix, coriander & annatto, sazon, dry                 0.0    17000.0   
Desserts, unsweetened, tablets, rennin                         0.0    26050.0   
Leavening agents, baking soda                                  0.0    27360.0   
Salt, table                                                    0.0    38758.0   

                                                    choline_mg  folate_mcg  \
name                                                                         
Beef,

In [225]:
#brain composition detour

In [226]:
nutrition.loc['Beef, simmered, cooked, brain, variety meats and by-products']

serving_size_g      100.00
calories            151.00
total_fat_g          11.00
saturated_fat_g       2.40
cholesterol_mg     3100.00
                    ...   
alcohol_g             0.00
ash_g                 1.46
caffeine_mg           0.00
theobromine_mg        0.00
water_g              74.86
Name: Beef, simmered, cooked, brain, variety meats and by-products, Length: 75, dtype: float64

In [227]:
nutrition.loc['Beef, simmered, cooked, brain, variety meats and by-products'].filter(like='_g')\
         .sort_values(ascending=False)

serving_size_g                   100.000
water_g                           74.860
protein_g                         11.670
total_fat_g                       11.000
fat_g                             10.530
saturated_fat_g                    2.400
saturated_fatty_acids_g            2.394
monounsaturated_fatty_acids_g      1.882
polyunsaturated_fatty_acids_g      1.632
carbohydrate_g                     1.480
ash_g                              1.460
alcohol_g                          0.000
glutamic_acid_g                    0.000
glycine_g                          0.000
alanine_g                          0.000
cystine_g                          0.000
aspartic_acid_g                    0.000
arginine_g                         0.000
isoleucine_g                       0.000
histidine_g                        0.000
methionine_g                       0.000
leucine_g                          0.000
lysine_g                           0.000
proline_g                          0.000
serine_g        

In [228]:
#Using Series between() with DFs.

In [229]:
nutrition.calories.head(10)

name
Cornstarch            381.0
Nuts, pecans          691.0
Eggplant, raw          25.0
Teff, uncooked        367.0
Sherbet, orange       144.0
Cauliflower, raw       25.0
Taro leaves, raw       42.0
Lamb, raw, ground     282.0
Cheese, camembert     300.0
Vegetarian fillets    290.0
Name: calories, dtype: float64

In [230]:
nutrition.calories.between(20,60)

name
Cornstarch                                                                                            False
Nuts, pecans                                                                                          False
Eggplant, raw                                                                                          True
Teff, uncooked                                                                                        False
Sherbet, orange                                                                                       False
                                                                                                      ...  
Beef, raw, all grades, trimmed to 0" fat, separable lean and fat, boneless, top round roast, round    False
Lamb, cooked, separable lean only, composite of trimmed retail cuts, frozen, imported, New Zealand    False
Lamb, raw, separable lean and fat, composite of trimmed retail cuts, frozen, imported, New Zealand    False
Beef, raw, all grades, 

In [231]:
nutrition[nutrition.calories.between(20, 60)]

serving_size_g  calories  \
name                                                                           
Eggplant, raw                                                100.0      25.0   
Cauliflower, raw                                             100.0      25.0   
Taro leaves, raw                                             100.0      42.0   
PACE, Picante Sauce                                          100.0      25.0   
Mango nectar, canned                                         100.0      51.0   
...                                                            ...       ...   
Beverages, added calcium, high vitamin C, great...           100.0      29.0   
Ruby Red grapefruit juice blend (grapefruit, gr...           100.0      44.0   
Beverages, prepared with water, frozen concentr...           100.0      45.0   
Apple juice, diluted with 3 volume water withou...           100.0      47.0   
Apple juice, with added ascorbic acid, diluted ...           100.0      47.0   

                                                    total_fat_g  \
name                                                              
Eggplant, raw                                               0.2   
Cauliflower, raw                                            0.3   
Taro leaves, raw                                            0.7   
PACE, Picante Sauce                                         0.0   
Mango nectar, canned                                        0.1   
...                                                         ...   
Beverages, added calcium, high vitamin C, great...          0.4   
Ruby Red grapefruit juice blend (grapefruit, gr...          0.1   
Beverages, prepared with water, frozen concentr...          0.0   
Apple juice, diluted with 3 volume water withou...          0.1   
Apple juice, with added ascorbic acid, diluted ...          0.1   

                                                    saturated_fat_g  \
name                                                                  
Eggplant, raw                                                   NaN   
Cauliflower, raw                                                0.1   
Taro leaves, raw                                                0.2   
PACE, Picante Sauce                                             NaN   
Mango nectar, canned                                            NaN   
...                                                             ...   
Beverages, added calcium, high vitamin C, great...              NaN   
Ruby Red grapefruit juice blend (grapefruit, gr...              NaN   
Beverages, prepared with water, frozen concentr...              NaN   
Apple juice, diluted with 3 volume water withou...              NaN   
Apple juice, with added ascorbic acid, diluted ...              NaN   

                                                    cholesterol_mg  sodium_mg  \
name                                                                            
Eggplant, raw                                                  0.0        2.0   
Cauliflower, raw                                               0.0       30.0   
Taro leaves, raw                                               0.0        3.0   
PACE, Picante Sauce                                            0.0      781.0   
Mango nectar, canned                                           0.0        5.0   
...                                                            ...        ...   
Beverages, added calcium, high vitamin C, great...             0.0       25.0   
Ruby Red grapefruit juice blend (grapefruit, gr...             0.0        8.0   
Beverages, prepared with water, frozen concentr...             0.0       10.0   
Apple juice, diluted with 3 volume water withou...             0.0        7.0   
Apple juice, with added ascorbic acid, diluted ...             0.0        7.0   

                                                    choline_mg  folate_mcg  \
name                                                                         
Eggpl

In [232]:
nutrition[nutrition.calories.between(20, 60)].sample(4)

serving_size_g  calories  \
name                                                                           
Babyfood, strained, vegetables and dumplings an...           100.0      48.0   
Fruit salad, solids and liquids, light syrup, c...           100.0      58.0   
Chives, raw                                                  100.0      30.0   
Peppers, raw, jalapeno                                       100.0      29.0   

                                                    total_fat_g  \
name                                                              
Babyfood, strained, vegetables and dumplings an...          0.9   
Fruit salad, solids and liquids, light syrup, c...          0.1   
Chives, raw                                                 0.7   
Peppers, raw, jalapeno                                      0.4   

                                                    saturated_fat_g  \
name                                                                  
Babyfood, strained, vegetables and dumplings an...              NaN   
Fruit salad, solids and liquids, light syrup, c...              NaN   
Chives, raw                                                     0.1   
Peppers, raw, jalapeno                                          0.1   

                                                    cholesterol_mg  sodium_mg  \
name                                                                            
Babyfood, strained, vegetables and dumplings an...             0.0       49.0   
Fruit salad, solids and liquids, light syrup, c...             0.0        6.0   
Chives, raw                                                    0.0        3.0   
Peppers, raw, jalapeno                                         0.0        3.0   

                                                    choline_mg  folate_mcg  \
name                                                                         
Babyfood, strained, vegetables and dumplings an...         0.0         7.0   
Fruit salad, solids and liquids, light syrup, c...         0.0         3.0   
Chives, raw                                                5.2       105.0   
Peppers, raw, jalapeno                                     7.5        27.0   

                                                    folic_acid_mcg  niacin_mg  \
name                                                                            
Babyfood, strained, vegetables and dumplings an...             0.0      0.574   
Fruit salad, solids and liquids, light syrup, c...             0.0      0.365   
Chives, raw                                                    0.0      0.647   
Peppers, raw, jalapeno                                         0.0      1.280   

                                                    ...  fat_g  \
name                                                ...          
Babyfood, strained, vegetables and dumplings an...  ...   0.90   
Fruit salad, solids and liquids, light syrup, c...  ...   0.07   
Chives, raw                                         ...   0.73   
Peppers, raw, jalapeno                              ...   0.37   

                                                    saturated_fatty_acids_g  \
name                                                                          
Babyfood, strained, vegetables and dumplings an...                    0.000   
Fruit salad, solids and liquids, light syrup, c...                    0.009   
Chives, raw                                                           0.146   
Peppers, raw, jalapeno                                                0.092   

                                                    monounsaturated_fatty_acids_g  \
name                                                                                
Babyfood, strained, vegetables and dumplings an...                          0.000   
Fruit salad, solids and liquids, light syrup, c...                          0.012   
Chives, raw                                                                 0.095   
P

#### Min, Max and Idx[MinMax]

In [233]:
nutrition.min()

serving_size_g     100.0
calories             0.0
total_fat_g          0.0
saturated_fat_g      0.1
cholesterol_mg       0.0
                   ...  
alcohol_g            0.0
ash_g                0.0
caffeine_mg          0.0
theobromine_mg       0.0
water_g              0.0
Length: 75, dtype: float64

In [234]:
nutrition.max()

serving_size_g      100.0
calories            902.0
total_fat_g         100.0
saturated_fat_g      96.0
cholesterol_mg     3100.0
                    ...  
alcohol_g            42.5
ash_g                99.8
caffeine_mg        5714.0
theobromine_mg     2634.0
water_g             100.0
Length: 75, dtype: float64

In [235]:
nutrition.min(axis=1)

name
Cornstarch                                                                                            0.0
Nuts, pecans                                                                                          0.0
Eggplant, raw                                                                                         0.0
Teff, uncooked                                                                                        0.0
Sherbet, orange                                                                                       0.0
                                                                                                     ... 
Beef, raw, all grades, trimmed to 0" fat, separable lean and fat, boneless, top round roast, round    0.0
Lamb, cooked, separable lean only, composite of trimmed retail cuts, frozen, imported, New Zealand    0.0
Lamb, raw, separable lean and fat, composite of trimmed retail cuts, frozen, imported, New Zealand    0.0
Beef, raw, all grades, trimmed to 0" fat,

In [236]:
#What food has d most potassium

In [237]:
nutrition.potassium_mg.max()

16500.0

In [238]:
nutrition.potassium_mg.sort_values(ascending=False)

name
Leavening agents, cream of tartar                      16500.0
Leavening agents, low-sodium, baking powder            10100.0
Parsley, freeze-dried                                   6300.0
Beverages, powder, unsweetened, instant, tea            6040.0
Beverages, unsweetened, decaffeinated, instant, tea     6040.0
                                                        ...   
Water, NAYA, non-carbonated, bottled                       0.0
Vitasoy USA Azumaya, Extra Firm Tofu                       0.0
Vitasoy USA Nasoya, Lite Silken Tofu                       0.0
SILK Vanilla soy yogurt (family size)                      0.0
KEEBLER, Honey Wheat Crackers, WHEATABLES                  0.0
Name: potassium_mg, Length: 8789, dtype: float64

In [239]:
nutrition.potassium_mg.nlargest(10)

name
Leavening agents, cream of tartar                         16500.0
Leavening agents, low-sodium, baking powder               10100.0
Parsley, freeze-dried                                      6300.0
Beverages, powder, unsweetened, instant, tea               6040.0
Beverages, unsweetened, decaffeinated, instant, tea        6040.0
Spices, dried, chervil                                     4740.0
Spices, dried, coriander leaf                              4466.0
Celery flakes, dried                                       4388.0
Beverages, powder, regular, instant, coffee                3535.0
Beverages, half the caffeine, regular, instant, coffee     3535.0
Name: potassium_mg, dtype: float64

In [240]:
nutrition.potassium_mg.idxmax()

'Leavening agents, cream of tartar'

In [241]:
nutrition.nsmallest(10, ['sodium_mg', 'calories', 'folate_mcg'])

serving_size_g  calories  \
name                                                                           
Beverages, well, tap, water                                  100.0       0.0   
Water, NAYA, non-carbonated, bottled                         100.0       0.0   
Beverages, decaffeinated, brewed, green, tea                 100.0       0.0   
Beverages, EVIAN, non-carbonated, bottled, water             100.0       0.0   
Beverages, CALISTOGA, non-carbonated, bottled, ...           100.0       0.0   
Beverages, DANNON, non-carbonated, bottled, water            100.0       0.0   
Sweetener, herbal extract powder from Stevia leaf            100.0       0.0   
Beverages, CRYSTAL GEYSER, non-carbonated, bott...           100.0       0.0   
Babyfood, without added fluoride., GERBER, bott...           100.0       0.0   
Beverages, AQUAFINA, PEPSI, non-carbonated, bot...           100.0       0.0   

                                                    total_fat_g  \
name                                                              
Beverages, well, tap, water                                 0.0   
Water, NAYA, non-carbonated, bottled                        0.0   
Beverages, decaffeinated, brewed, green, tea                0.0   
Beverages, EVIAN, non-carbonated, bottled, water            0.0   
Beverages, CALISTOGA, non-carbonated, bottled, ...          0.0   
Beverages, DANNON, non-carbonated, bottled, water           0.0   
Sweetener, herbal extract powder from Stevia leaf           0.0   
Beverages, CRYSTAL GEYSER, non-carbonated, bott...          0.0   
Babyfood, without added fluoride., GERBER, bott...          0.0   
Beverages, AQUAFINA, PEPSI, non-carbonated, bot...          0.0   

                                                    saturated_fat_g  \
name                                                                  
Beverages, well, tap, water                                     NaN   
Water, NAYA, non-carbonated, bottled                            NaN   
Beverages, decaffeinated, brewed, green, tea                    NaN   
Beverages, EVIAN, non-carbonated, bottled, water                NaN   
Beverages, CALISTOGA, non-carbonated, bottled, ...              NaN   
Beverages, DANNON, non-carbonated, bottled, water               NaN   
Sweetener, herbal extract powder from Stevia leaf               NaN   
Beverages, CRYSTAL GEYSER, non-carbonated, bott...              NaN   
Babyfood, without added fluoride., GERBER, bott...              NaN   
Beverages, AQUAFINA, PEPSI, non-carbonated, bot...              NaN   

                                                    cholesterol_mg  sodium_mg  \
name                                                                            
Beverages, well, tap, water                                    0.0        0.0   
Water, NAYA, non-carbonated, bottled                           0.0        0.0   
Beverages, decaffeinated, brewed, green, tea                   0.0        0.0   
Beverages, EVIAN, non-carbonated, bottled, water               0.0        0.0   
Beverages, CALISTOGA, non-carbonated, bottled, ...             0.0        0.0   
Beverages, DANNON, non-carbonated, bottled, water              0.0        0.0   
Sweetener, herbal extract powder from Stevia leaf              0.0        0.0   
Beverages, CRYSTAL GEYSER, non-carbonated, bott...             0.0        0.0   
Babyfood, without added fluoride., GERBER, bott...             0.0        0.0   
Beverages, AQUAFINA, PEPSI, non-carbonated, bot...             0.0        0.0   

                                                    choline_mg  folate_mcg  \
name                                                                         
Beverages, well, tap, water                                0.0         0.0   
Water, NAYA, non-carbonated, bottled                       0.0         0.0   
Beverages, decaffeinated, brewed, green, tea               0.0         0.0   
Beverages, EVIAN, non-carbonated, bottled, water           0.0        

#### Skill Challenge

##### 1. Find the 10 foods that have the most VitaminB12. What do they have in common?

In [242]:
nutrition['vitamin_b12_mcg'].nlargest(10)

name
Mollusks, moist heat, cooked, mixed species, clam                                   98.89
Beef, boiled, cooked, variety meats and by-products liver, imported, New Zealand    96.00
Lamb, raw, liver, variety meats and by-products                                     90.05
Lamb, pan-fried, cooked, liver, variety meats and by-products                       85.70
Veal, braised, cooked, liver, variety meats and by-products                         84.60
Beef, raw, liver, variety meats and by-products, imported, New Zealand              84.50
Beef, pan-fried, cooked, liver, variety meats and by-products                       83.13
Lamb, braised, cooked, kidneys, variety meats and by-products                       78.90
Lamb, braised, cooked, liver, variety meats and by-products                         76.50
Veal, pan-fried, cooked, liver, variety meats and by-products                       72.50
Name: vitamin_b12_mcg, dtype: float64

The conclusion from foods that have the most VitaminB12 is that they are either cooked, Lamb liver, Beef liver or
by-products. In short, they are all animal products

In [243]:
nut_eggplant = nutrition.filter(axis=0, regex='(?i)eggplant')

In [244]:
nut_eggplant['sodium_mg'].nlargest()

name
Eggplant, pickled                                  1674.0
Eggplant, with salt, drained, boiled, cooked        239.0
Eggplant, raw                                         2.0
Eggplant, without salt, drained, boiled, cooked       1.0
Name: sodium_mg, dtype: float64

In [245]:
#OR
nut_eggplant.sodium_mg.max()

1674.0

The eggplant like food with the most sodium is Eggplant, pickled with 1674.0mg

##### 3. Select a slice of the dataframe that contains 4 random rows and 2 columns.

#### Another Skill Challenge

1. Remove all the food items that contains at least one NaN. Do this in a way that modifies the dataframe,i.e changes the stick.
How many food items remain after the exclusions?

In [246]:
new_trition = nutrition.dropna(axis=0)

In [247]:
new_trition.shape[0]

7199

In [248]:
#OR
nutrition.dropna(axis=0, inplace=True)

In [249]:
nutrition.shape[0]

7199

There are 7,199 food items left after the exclusions.

#### 2. From the remaining records, isolate those that have between 20 and 40mg of Vitamin C per 100g serving. Of these foods, which one is the least caloric, i.e has the minimum calories?

In [250]:
nutrition.filter(axis=1, regex='(?i)vitamin_c_mg')

vitamin_c_mg
name                                                            
Nuts, pecans                                                 1.1
Teff, uncooked                                               0.0
Sherbet, orange                                              2.3
Cauliflower, raw                                            48.2
Taro leaves, raw                                            52.0
...                                                          ...
Beef, raw, all grades, trimmed to 0" fat, separ...           0.0
Lamb, cooked, separable lean only, composite of...           0.0
Lamb, raw, separable lean and fat, composite of...           0.0
Beef, raw, all grades, trimmed to 0" fat, separ...           0.0
Beef, raw, all grades, trimmed to 0" fat, separ...           0.0

[7199 rows x 1 columns]

In [251]:
nutrition[['vitamin_c_mg', 'serving_size_g']]

vitamin_c_mg  \
name                                                               
Nuts, pecans                                                 1.1   
Teff, uncooked                                               0.0   
Sherbet, orange                                              2.3   
Cauliflower, raw                                            48.2   
Taro leaves, raw                                            52.0   
...                                                          ...   
Beef, raw, all grades, trimmed to 0" fat, separ...           0.0   
Lamb, cooked, separable lean only, composite of...           0.0   
Lamb, raw, separable lean and fat, composite of...           0.0   
Beef, raw, all grades, trimmed to 0" fat, separ...           0.0   
Beef, raw, all grades, trimmed to 0" fat, separ...           0.0   

                                                    serving_size_g  
name                                                                
Nuts, pecans                                                 100.0  
Teff, uncooked                                               100.0  
Sherbet, orange                                              100.0  
Cauliflower, raw                                             100.0  
Taro leaves, raw                                             100.0  
...                                                            ...  
Beef, raw, all grades, trimmed to 0" fat, separ...           100.0  
Lamb, cooked, separable lean only, composite of...           100.0  
Lamb, raw, separable lean and fat, composite of...           100.0  
Beef, raw, all grades, trimmed to 0" fat, separ...           100.0  
Beef, raw, all grades, trimmed to 0" fat, separ...           100.0  

[7199 rows x 2 columns]

In [252]:
nutrition[nutrition.vitamin_c_mg.between(20, 40)].shape[0]

242

In [253]:
nutrition[nutrition.vitamin_c_mg.between(20, 40)].calories.nsmallest(1)

name
Asparagus, with salt, drained, boiled, cooked, frozen    18.0
Name: calories, dtype: float64

<b>Observation</b>: There are 242 foods that has between 20 and 40mg of Vitamin C.<br>
<b>Conclusion</b>: Asparagus, with salt, drained, boiled, cooked, frozen has the minimum calories of 18.0

##### 3. How many food items in the dataframe have Vitamin C levels of between 2 and 3 standard deviations above the mean?

In [254]:
m = nutrition.vitamin_c_mg.mean()

In [255]:
stnd = nutrition.vitamin_c_mg.std()

In [256]:
t_std = 2*stnd + m
th_std = 3*stnd + m

In [257]:
nutrition[nutrition.vitamin_c_mg.between(t_std, th_std)].shape[0]

17

There are 17 food items that has Vitamin C levels of between 2 and 3 standard deviations above the mean.

In [258]:
result_set = nutrition[nutrition.vitamin_c_mg.between(t_std, th_std)]

In [259]:
result_set.describe()

serving_size_g    calories  total_fat_g  saturated_fat_g  \
count            17.0   17.000000    17.000000        17.000000   
mean            100.0  254.588235     4.129412         0.964706   
std               0.0  140.672074     4.693581         1.134648   
min             100.0   29.000000     0.400000         0.100000   
25%             100.0  146.000000     0.800000         0.100000   
50%             100.0  302.000000     3.000000         0.700000   
75%             100.0  371.000000     5.100000         1.400000   
max             100.0  422.000000    14.000000         4.500000   

       cholesterol_mg   sodium_mg  choline_mg  folate_mcg  folic_acid_mcg  \
count       17.000000   17.000000   17.000000   17.000000       17.000000   
mean         3.411765  267.588235   32.994118  139.882353       72.058824   
std         10.718319  215.914062   66.390535  150.379887      151.563712   
min          0.000000    3.000000    0.000000    0.000000        0.000000   
25%          0.000000   56.000000    0.000000   23.000000        0.000000   
50%          0.000000  317.000000    7.500000  120.000000        0.000000   
75%          0.000000  429.000000   24.500000  180.000000        0.000000   
max         44.000000  717.000000  266.900000  500.000000      500.000000   

       niacin_mg  ...      fat_g  saturated_fatty_acids_g  \
count  17.000000  ...  17.000000                17.000000   
mean    7.618235  ...   4.112941                 0.946882   
std    10.817866  ...   4.663148                 1.136581   
min     0.000000  ...   0.370000                 0.062000   
25%     1.000000  ...   0.790000                 0.092000   
50%     3.397000  ...   3.000000                 0.672000   
75%     9.943000  ...   5.100000                 1.360000   
max    38.442000  ...  14.080000                 4.499000   

       monounsaturated_fatty_acids_g  polyunsaturated_fatty_acids_g  \
count                      17.000000                      17.000000   
mean                        1.768353                       0.954471   
std                         2.854251                       1.288771   
min                         0.029000                       0.093000   
25%                         0.063000                       0.124000   
50%                         0.704000                       0.338000   
75%                         1.724000                       1.070000   
max                         9.110000                       4.804000   

       fatty_acids_total_trans_mg  alcohol_g      ash_g  caffeine_mg  \
count                   17.000000       17.0  17.000000    17.000000   
mean                     3.411765        0.0   3.882941     3.705882   
std                     10.718319        0.0   3.492880    12.726767   
min                      0.000000        0.0   0.530000     0.000000   
25%                      0.000000        0.0   1.000000     0.000000   
50%                      0.000000        0.0   2.840000     0.000000   
75%                      0.000000        0.0   5.530000     0.000000   
max                     44.000000        0.0  11.360000    52.000000   

       theobromine_mg    water_g  
count       17.000000  17.000000  
mean        41.588235  31.429412  
std        147.915119  36.400353  
min          0.000000   2.000000  
25%          0.000000   5.890000  
50%          0.000000  10.200000  
75%          0.000000  62.000000  
max        608.000000  91.690000  

[8 rows x 75 columns]